force-app/main/default/objects/Job_Role__c/Job_Role__c.object-meta.xml
<CustomObject>
    <description
  >Specifies a job role at an Account that can be associated with a contact.</description>
    <label>Job Role</label>
    <nameField>
        <displayFormat>R{000000}</displayFormat>
        <label>Job Role</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Role__c/fields/Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email__c</fullName>
    <formula>Contact__r.Email</formula>
    <label>Contact: Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/contact_from_role_apexcontroller_test.cls
@isTest
public with sharing class contact_from_role_apexcontroller_test {
  static testMethod void test() {
    Contact c = testData.createContact();
    Job_Role__c r = testData.createRole(c);
    contact_from_role_apexcontroller.getRole(r.Id);
    Contact c2 = contact_from_role_apexcontroller.getContact(r.Id);
    c2.email = r.Contact_Email__c;
    String result = contact_from_role_apexcontroller.saveContact(c2);
    System.Debug(' ------DONE ----- ' + result);
  }
}