force-app/main/default/objects/Job_Role__c/Job_Role__c.object-meta.xml
<CustomObject>
    <description
  >Specifies a job role at an Account that can be associated with a contact.</description>
    <label>Job Role</label>
    <nameField>
        <displayFormat>R{000000}</displayFormat>
        <label>Job Role</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Role__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job Roles</relationshipLabel>
    <relationshipName>Job_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Role__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Job Role Department</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Role__c/fields/Job_Role_Email__c.field-meta.xml
<CustomField>
    <fullName>Job_Role_Email__c</fullName>
    <label>Job Role Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Job_Role__c/fields/Job_Role_Mailing_City__c.field-meta.xml
<CustomField>
    <fullName>Job_Role_Mailing_City__c</fullName>
    <label>Job Role Mailing City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Role__c/fields/Job_Role_Mailing_State__c.field-meta.xml
<CustomField>
    <fullName>Job_Role_Mailing_State__c</fullName>
    <label>Job Role Mailing State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Role__c/fields/Job_Role_Mailing_Street_2__c.field-meta.xml
<CustomField>
    <fullName>Job_Role_Mailing_Street_2__c</fullName>
    <label>Job Role Mailing Street 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Role__c/fields/Job_Role_Mailing_Street__c.field-meta.xml
<CustomField>
    <fullName>Job_Role_Mailing_Street__c</fullName>
    <label>Job Role Mailing Street</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Role__c/fields/Job_Role_Mailing_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Job_Role_Mailing_Zip_Code__c</fullName>
    <label>Job Role Mailing Zip Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Role__c/fields/Job_Role_Organization__c.field-meta.xml
<CustomField>
    <fullName>Job_Role_Organization__c</fullName>
    <label>Job Role Organization</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Role__c/fields/Job_Role_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Role_Phone_Number__c</fullName>
    <label>Job Role Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Job_Role__c/fields/Job_Role_Phone_Number_Extension__c.field-meta.xml
<CustomField>
    <fullName>Job_Role_Phone_Number_Extension__c</fullName>
    <label>Job Role Phone Number Extension</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Role__c/fields/Job_Role_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Role_Title__c</fullName>
    <label>Job Role Title</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/contact_from_role_apexcontroller.cls
public with sharing class contact_from_role_apexcontroller {
  public static ID contactId = null;
  public static Contact c;

  //public void contact_from_role_apexcontroller(){}

  @AuraEnabled
  public static Job_Role__c getRole(Id roleId) {
    List<Job_Role__c> roles = [
      SELECT
        Id,
        Contact__c,
        Job_Role_Title__c,
        Department__c,
        Job_Role_Organization__c,
        Job_Role_Mailing_Street__c,
        Job_Role_Mailing_Street_2__c,
        Job_Role_Mailing_City__c,
        Job_Role_Mailing_State__c,
        Job_Role_Mailing_Zip_Code__c,
        Job_Role_Email__c,
        Job_Role_Phone_Number__c,
        Job_Role_Phone_Number_Extension__c
      FROM Job_Role__c
      WHERE Id = :roleId
      LIMIT 1
    ];
    if (!roles.isEmpty()) {
      Job_Role__c r = roles[0];
      contactId = r.Contact__c;
      c = [
        SELECT
          Id,
          Name,
          Title,
          Department,
          Company_Name_Holder__c,
          MailingCity,
          MailingState,
          MailingCountry,
          MailingPostalCode,
          MailingStreet,
          Email,
          Phone,
          Phone_Extension__c
        FROM Contact
        WHERE id = :contactId
        LIMIT 1
      ];
      return r;
    }
    return null;
  }

  @AuraEnabled
  public static Contact getContact(Id roleId) {
    if (contactId == null) {
      List<Job_Role__c> roles = [
        SELECT Id, Contact__c
        FROM Job_Role__c
        WHERE Id = :roleId
        LIMIT 1
      ];
      if (!roles.isEmpty()) {
        Job_Role__c r = roles[0];
        contactId = r.Contact__c;
      }
    }

    c = [
      SELECT
        Id,
        Name,
        Title,
        Department,
        Company_Name_Holder__c,
        MailingCity,
        MailingState,
        MailingCountry,
        MailingPostalCode,
        MailingStreet,
        Email,
        Phone,
        Phone_Extension__c
      FROM Contact
      WHERE id = :contactId
      LIMIT 1
    ];
    return c;
  }

  @AuraEnabled
  public static String saveContact(Contact contact) {
    List<Contact> contacts = new List<Contact>();
    contacts.add(contact);

    Database.UpsertResult[] results = Database.upsert(contacts, false);
    if (results[0].isSuccess())
      return 'Success';
    else {
      Database.Error[] errors = results[0].getErrors();
      return errors[0].getMessage();
    }
  }
}