force-app/main/default/objects/Privacy_Request__c/Privacy_Request__c.object-meta.xml
<CustomObject>
    <description
  >Object used for keeping record of all privacy requests such as right to delete, right to opt-out and right to know.  Used for CCPA compliance.</description>
    <label>Privacy Request</label>
    <nameField>
        <displayFormat>PR-{000}</displayFormat>
        <label>Privacy Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Privacy Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Privacy_Request__c/fields/Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_1__c</fullName>
    <label>Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Privacy_Request__c/fields/Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_2__c</fullName>
    <label>Address Line 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Privacy_Request__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Privacy_Request__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Privacy_Request__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Privacy_Request__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Privacy_Request__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Privacy_Request__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <label>Organization</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Privacy_Request__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Privacy_Request__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PrivacyRequestController_test.cls
@isTest
public class PrivacyRequestController_test {
  public static testMethod void testPrivacyReqController() {
    PrivacyRequestController testCtrl = new PrivacyRequestController();
    List<selectOption> stateOpts = testCtrl.getStateOptions();
    System.assertEquals(stateOpts.size(), 77);

    List<selectOption> requestType = testCtrl.getRequestType();
    System.assert(requestType.size() > 1);

    Privacy_Request__c pr = testCtrl.getThePrivacyRequest();
    Test.startTest();
    Test.setMock(HttpCalloutMock.class, new MockCaptchaValidation(true)); // Pass the expected validation result
    // Instantiate a new controller with all parameters in the page
    PrivacyRequestController ctrl = makePrivacyRequest(
      new PrivacyRequestController()
    );
    ApexPages.currentPage().getParameters().put('TimeSpent', '20.0');
    PageReference res = ctrl.submit();
    Test.stopTest();

    // Verify that the success page displays
    //System.assertEquals('/apex/PrivacyRequest?s=1', res.getUrl());

    Privacy_Request__c pr_res = [
      SELECT
        First_Name__c,
        Last_Name__c,
        Phone__c,
        Email__c,
        Organization__c,
        Address_Line_1__c,
        Address_Line_2__c,
        City__c,
        State__c,
        Zip__c,
        Comments__c
      FROM Privacy_Request__c
      ORDER BY CreatedDate DESC
      LIMIT 1
    ];

    System.assertEquals('Joe', pr_res.First_Name__c);
    System.assertEquals('McTesterson', pr_res.Last_Name__c);
    System.assertEquals('(999) 999-9999', pr_res.Phone__c);
    System.assertEquals('j.mctest@gmail.net', pr_res.Email__c);
    System.assertEquals('Testsers Inc.', pr_res.Organization__c);
    System.assertEquals('100 Blue Ravine Rd.', pr_res.Address_Line_1__c);
    System.assertEquals(null, pr_res.Address_Line_2__c);
    System.assertEquals('Folsom', pr_res.City__c);
    System.assertEquals('CA', pr_res.State__c);
    System.assertEquals('95630', pr_res.Zip__c);
    System.assertEquals('Please Dont Sell!', pr_res.Comments__c);
  }

  private static PrivacyRequestController makePrivacyRequest(
    PrivacyRequestController ctrl
  ) {
    ctrl.First_Name = 'Joe';
    ctrl.Last_Name = 'McTesterson';
    ctrl.Phone = '(999) 999-9999';
    ctrl.Email = 'j.mctest@gmail.net';
    ctrl.Organization = 'Testsers Inc.';
    ctrl.Address_Line_1 = '100 Blue Ravine Rd.';
    ctrl.Address_Line_2 = '';
    ctrl.City = 'Folsom';
    ctrl.State = 'CA';
    ctrl.Zip = '95630';
    ctrl.Comments = 'Please Dont Sell!';
    ctrl.recaptchaToken = 'valid_recaptcha_token';
    ctrl.isChecked = true;
    return ctrl;
  }
}