force-app/main/default/objects/Account_Durable_History__c/Account_Durable_History__c.object-meta.xml
<CustomObject>
    <description
  >Keeps a history of accounts that have been merged or deleted so that external systems can puzzle broken Id links.</description>
    <label>Account Durable History</label>
    <nameField>
        <displayFormat>ADH-{0000}</displayFormat>
        <label>Account Durable History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounts Durable History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Durable_History__c/fields/Account_Deleted_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Deleted_Id__c</fullName>
    <description
  >This is a record of the Salesforce Id of the &apos;losing&apos; record and/or record that was deleted.</description>
    <inlineHelpText
  >This is a record of the Salesforce Id of the &apos;losing&apos; record and/or record that was deleted.</inlineHelpText>
    <label>Account Deleted Id</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Durable_History__c/fields/Account_Reference__c.field-meta.xml
<CustomField>
    <fullName>Account_Reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description
  >When an account is merged, this refers to the &apos;winning&apos; record.</description>
    <inlineHelpText
  >When an account is merged, this refers to the &apos;winning&apos; record.</inlineHelpText>
    <label>Account Reference</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts Durable History</relationshipLabel>
    <relationshipName>Accounts_Durable_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Account_After_Delete_Test.cls
@isTest
public class Account_After_Delete_Test {
  static testMethod void testDeleteAccount() {
    Test.startTest();
    Account act = testData.createAccount(true);
    String actid = String.valueOf(act.Id).substring(0, 15);
    delete act;
    Account_Durable_History__c acdh = [
      SELECT Id, Account_Reference__c, Account_Deleted_Id__c
      FROM Account_Durable_History__c
      WHERE Account_Deleted_Id__c = :actid
    ];
    System.assertEquals(acdh.Account_Deleted_Id__c, actid);
    System.assertEquals(acdh.Account_Reference__c, null);
    Test.stopTest();
  }
  static testMethod void testMergeAccount() {
    Test.startTest();
    Account act = testData.createAccount(true);
    Id master = act.Id;
    Account losingAct = testData.createAccount(true);
    update losingAct;
    String losingId = String.valueOf(losingAct.Id).substring(0, 15);
    merge act losingAct;
    Account_Durable_History__c acdh = [
      SELECT Id, Account_Reference__c, Account_Deleted_Id__c
      FROM Account_Durable_History__c
      WHERE Account_Reference__c = :master
    ];
    System.assertEquals(acdh.Account_Deleted_Id__c, losingId);
    System.assertEquals(acdh.Account_Reference__c, master);
    Test.stopTest();
  }
}