force-app/main/default/objects/Contact_Durable_History__c/Contact_Durable_History__c.object-meta.xml
<CustomObject>
    <description>Provides a record of merged and deleted contacts.</description>
    <label>Contact Durable History</label>
    <nameField>
        <displayFormat>CDH-{0000}</displayFormat>
        <label>Contact Durable History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contacts Durable History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Durable_History__c/fields/Contact_Deleted_CMS_Id__c.field-meta.xml
<CustomField>
    <fullName>Contact_Deleted_CMS_Id__c</fullName>
    <description
  >The CMS ID of the deleted contact record (if it had one)</description>
    <inlineHelpText
  >The CMS ID of the deleted contact record (if it had one)</inlineHelpText>
    <label>Contact Deleted CMS Id</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact_Durable_History__c/fields/Contact_Deleted_Id__c.field-meta.xml
<CustomField>
    <fullName>Contact_Deleted_Id__c</fullName>
    <description
  >This is a record of the Salesforce Id of the record deleted.</description>
    <inlineHelpText
  >This is a record of the Salesforce Id of the record deleted.</inlineHelpText>
    <label>Contact Deleted Id</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Durable_History__c/fields/Contact_Reference__c.field-meta.xml
<CustomField>
    <fullName>Contact_Reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description
  >When a contact is merged, this refers to the &apos;winning&apos; record.</description>
    <inlineHelpText
  >When a contact is merged, this refers to the &apos;winning&apos; record.</inlineHelpText>
    <label>Contact Reference</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts Durable History</relationshipLabel>
    <relationshipName>Contacts_Durable_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Contact_After_Delete_Test.cls
@isTest
public class Contact_After_Delete_Test {
  static testMethod void testDeleteContact() {
    Test.startTest();
    Contact ct = testData.createContact(true);
    String ctid = String.valueOf(ct.Id).substring(0, 15);
    delete ct;
    Contact_Durable_History__c cdh = [
      SELECT
        Id,
        Contact_Deleted_CMS_Id__c,
        Contact_Reference__c,
        Contact_Deleted_Id__c
      FROM Contact_Durable_History__c
      WHERE Contact_Deleted_Id__c = :ctid
    ];
    System.assertEquals(cdh.Contact_Deleted_Id__c, ctid);
    System.assertEquals(cdh.Contact_Reference__c, null);
    System.assertEquals(cdh.Contact_Deleted_CMS_Id__c, null);
    Test.stopTest();
  }
  static testMethod void testMergeContact() {
    Test.startTest();
    Contact ct = testData.createContact(true);
    Id master = ct.Id;
    Contact losingCt = testData.createContact(true);
    losingCt.CMS_Contact_Id__c = '12342333';
    update losingCt;
    String losingId = String.valueOf(losingCt.Id).substring(0, 15);
    merge ct losingCt;
    Contact_Durable_History__c cdh = [
      SELECT
        Id,
        Contact_Deleted_CMS_Id__c,
        Contact_Reference__c,
        Contact_Deleted_Id__c
      FROM Contact_Durable_History__c
      WHERE Contact_Reference__c = :master
    ];
    System.assertEquals(cdh.Contact_Deleted_Id__c, losingId);
    System.assertEquals(cdh.Contact_Reference__c, master);
    System.assertEquals(cdh.Contact_Deleted_CMS_Id__c, 12342333);
    Test.stopTest();
  }
}