force-app/main/default/objects/Events__c/Events__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >Standard_Event_Compact_Layout</compactLayoutAssignment>
    <description
  >These are e.Republic Events - tradeshows, executive events, webinars, roundtables, custom events, etc.</description>
    <label>Event or Conference</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events and Conferences</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Events__c/fields/Advisory_Board_1__c.field-meta.xml
<CustomField>
    <fullName>Advisory_Board_1__c</fullName>
    <description
  >The date of the first Advisory Board meeting for this event</description>
    <inlineHelpText
  >The date of the first Advisory Board meeting for this event</inlineHelpText>
    <label>Advisory Board #1</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Advisory_Board_2__c.field-meta.xml
<CustomField>
    <fullName>Advisory_Board_2__c</fullName>
    <description
  >The date of the second Advisory Board meeting for this event</description>
    <inlineHelpText
  >The date of the second Advisory Board meeting for this event</inlineHelpText>
    <label>Advisory Board #2</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <description
  >The primary brand of the event. Event may still be listed on multiple websites.</description>
    <inlineHelpText
  >The primary brand of the event. Event may still be listed on multiple websites.</inlineHelpText>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>GOVERNING</fullName>
            </value>
            <value>
                <fullName>GOVTECH</fullName>
            </value>
            <value>
                <fullName>PCIO</fullName>
            </value>
            <value>
                <fullName>CDE</fullName>
            </value>
            <value>
                <fullName>CDG</fullName>
            </value>
            <value>
                <fullName>EMERGENCYMGMT</fullName>
            </value>
            <value>
                <fullName>EREPUBLIC</fullName>
            </value>
            <value>
                <fullName>DIGITAL_COMMUNITIES</fullName>
            </value>
            <value>
                <fullName>FUTURE_STRUCTURE</fullName>
            </value>
            <value>
                <fullName>INSIDER CA</fullName>
            </value>
            <value>
                <fullName>INSIDER TX</fullName>
            </value>
            <value>
                <fullName>INSIDER FL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Events__c/fields/Event_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_End_Date__c</fullName>
    <description>This is the end date of the event.</description>
    <inlineHelpText>This is the end date of the event.</inlineHelpText>
    <label>Event End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Event_Quarter__c.field-meta.xml
<CustomField>
    <fullName>Event_Quarter__c</fullName>
    <description
  >This is the quarter of the year in which the event will take place.</description>
    <inlineHelpText
  >This is the quarter of the year in which the event will take place.</inlineHelpText>
    <label>Event Quarter</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Q1</fullName>
            </value>
            <value>
                <fullName>Q2</fullName>
            </value>
            <value>
                <fullName>Q3</fullName>
            </value>
            <value>
                <fullName>Q4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Events__c/fields/Event_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_Start_Date__c</fullName>
    <description>This is the start date of the event.</description>
    <inlineHelpText>This is the start date of the event.</inlineHelpText>
    <label>Event Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Event_Year__c.field-meta.xml
<CustomField>
    <fullName>Event_Year__c</fullName>
    <description
  >Specify the year of the event for reporting purposes. [HOTS PACKET]</description>
    <inlineHelpText
  >Specify the year of the event for reporting purposes.  [HOTS PACKET]</inlineHelpText>
    <label>Event Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/last_years_event__c.field-meta.xml
<CustomField>
    <fullName>last_years_event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Last Years Event</label>
    <referenceTo>Events__c</referenceTo>
    <relationshipName>Events_and_Conferences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Nickname__c.field-meta.xml
<CustomField>
    <fullName>Nickname__c</fullName>
    <description
  >This is a short version of the event&apos;s name used for reporting purposes.</description>
    <inlineHelpText
  >This is a short version of the event&apos;s name used for reporting purposes.</inlineHelpText>
    <label>Nickname</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Program_Guide_Sponsor_Deadline__c.field-meta.xml
<CustomField>
    <fullName>Program_Guide_Sponsor_Deadline__c</fullName>
    <description
  >Program Guide Sponsor Deadline (profile and logo; sponsor ads)</description>
    <inlineHelpText
  >Program Guide Sponsor Deadline (profile and logo; sponsor ads)</inlineHelpText>
    <label>Pgm Guide or SAG Sponsor Deadline EOD</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Sponsorship_Revenue_Target__c.field-meta.xml
<CustomField>
    <fullName>Sponsorship_Revenue_Target__c</fullName>
    <label>Sponsorship Revenue Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/eventHotPacketController.cls
public with sharing class eventHotPacketController {
  public List<eventHotSheet> HotSheets = new List<eventHotSheet>();
  public Integer Quarter { get; set; }
  public Integer Year { get; set; }
  public Date StartDate { get; set; }
  public Date EndDate { get; set; }

  // Cover page properties
  public Decimal WonTotal { get; set; }
  public Decimal HotTotal { get; set; }
  public Decimal WarmTotal { get; set; }
  public Decimal MissingTotal { get; set; }
  public Decimal TargetTotal { get; set; }
  public Decimal RevenueDifference { get; set; }
  public String Brand { get; set; }

  public Date UpdateDate { get; set; }

  public eventHotPacketController() {
    Quarter = Integer.valueof(
      ApexPages.currentPage().getParameters().get('quarter')
    );
    Year = Integer.valueof(ApexPages.currentPage().getParameters().get('year'));
    UpdateDate = date.today();

    if (Quarter == 1) {
      StartDate = date.newInstance(Year, 1, 1);
      EndDate = date.newInstance(Year, 3, 31);
    } else if (Quarter == 2) {
      StartDate = date.newInstance(Year, 4, 1);
      EndDate = date.newInstance(Year, 6, 30);
    } else if (Quarter == 3) {
      StartDate = date.newInstance(Year, 7, 1);
      EndDate = date.newInstance(Year, 9, 30);
    } else if (Quarter == 4) {
      StartDate = date.newInstance(Year, 10, 1);
      EndDate = date.newInstance(Year, 12, 31);
    }

    WonTotal = 0;
    HotTotal = 0;
    WarmTotal = 0;
    MissingTotal = 0;
    TargetTotal = 0;
    RevenueDifference = 0;
    eventHotSheet hotSheet;

    String event_brand = ApexPages.currentPage().getParameters().get('brand');
    Brand = event_brand;
    String quart = 'Q' + Quarter;

    for (Events__c event : [
      SELECT
        Id,
        Name,
        Nickname__c,
        Event_Start_Date__c,
        Event_End_Date__c,
        Event_Year__c,
        Sponsorship_Revenue_Target__c,
        last_years_event__r.Id,
        last_years_event__r.Name,
        last_years_event__r.Nickname__c,
        last_years_event__r.Event_Start_Date__c,
        last_years_event__r.Event_End_Date__c,
        Advisory_Board_1__c,
        Advisory_Board_2__c,
        Program_Guide_Sponsor_Deadline__c
      FROM Events__c
      WHERE
        ((Event_Start_Date__c >= :startDate
        AND Event_Start_Date__c <= :endDate)
        OR (Event_Year__c = :Year
        AND Event_Quarter__c = :quart))
        AND Brand__c = :event_brand
        AND RecordTypeId IN (
          SELECT Id
          FROM RecordType
          WHERE Name = 'Standard Event'
        )
      ORDER BY Event_Start_Date__c
    ]) {
      hotSheet = new eventHotSheet(event);
      WonTotal += hotSheet.WonTotal;
      HotTotal += hotSheet.HotTotal;
      WarmTotal += hotSheet.WarmTotal;
      MissingTotal += hotSheet.MissingTotal;
      if (hotSheet.revenueTarget != null) {
        TargetTotal += hotSheet.revenueTarget;
      }
      if (hotSheet.revenueDifference != null) {
        RevenueDifference += hotSheet.revenueDifference;
      }

      HotSheets.add(hotSheet);
    }
  }

  public List<eventHotSheet> getHotSheets() {
    return HotSheets;
  }
}