force-app/main/default/objects/Events__c/Events__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >Standard_Event_Compact_Layout</compactLayoutAssignment>
    <description
  >These are e.Republic Events - tradeshows, executive events, webinars, roundtables, custom events, etc.</description>
    <label>Event or Conference</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events and Conferences</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Events__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <description
  >The primary brand of the event. Event may still be listed on multiple websites.</description>
    <inlineHelpText
  >The primary brand of the event. Event may still be listed on multiple websites.</inlineHelpText>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>GOVERNING</fullName>
            </value>
            <value>
                <fullName>GOVTECH</fullName>
            </value>
            <value>
                <fullName>PCIO</fullName>
            </value>
            <value>
                <fullName>CDE</fullName>
            </value>
            <value>
                <fullName>CDG</fullName>
            </value>
            <value>
                <fullName>EMERGENCYMGMT</fullName>
            </value>
            <value>
                <fullName>EREPUBLIC</fullName>
            </value>
            <value>
                <fullName>DIGITAL_COMMUNITIES</fullName>
            </value>
            <value>
                <fullName>FUTURE_STRUCTURE</fullName>
            </value>
            <value>
                <fullName>INSIDER CA</fullName>
            </value>
            <value>
                <fullName>INSIDER TX</fullName>
            </value>
            <value>
                <fullName>INSIDER FL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >Registration_Compact_Layout</compactLayoutAssignment>
    <description
  >This is a registration for any event, conference, forum, webinar, etc. across all e.Republic business units.</description>
    <label>Registration</label>
    <nameField>
        <displayFormat>REG-{000000}</displayFormat>
        <label>Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <formula>Text ( Event__r.Brand__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Brand</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Events__c</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Exclude_From_Mailing_List__c.field-meta.xml
<CustomField>
    <fullName>Exclude_From_Mailing_List__c</fullName>
    <defaultValue>false</defaultValue>
    <description
  >Excludes registrant from the mailing list for this event.</description>
    <inlineHelpText
  >Check here to exclude this registrant from the mailing list for this event only.</inlineHelpText>
    <label>Exclude From Mailing List?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Reg_Type__c.field-meta.xml
<CustomField>
    <fullName>Reg_Type__c</fullName>
    <inlineHelpText
  >Enter the type of registration i.e. Sponsor, Speaker, etc.</inlineHelpText>
    <label>Reg Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Association</fullName>
            </value>
            <value>
                <fullName>Govt Attendee</fullName>
                <default>true</default>
                <label>Govt Attendee</label>
            </value>
            <value>
                <fullName>Industry Attendee</fullName>
            </value>
            <value>
                <fullName>Sponsor</fullName>
            </value>
            <value>
                <fullName>Press</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>1</fullName>
                <isActive>false</isActive>
                <label>1</label>
            </value>
            <value>
                <fullName>ABSPON</fullName>
                <isActive>false</isActive>
                <label>ABSPON</label>
            </value>
            <value>
                <fullName>ADBD</fullName>
                <isActive>false</isActive>
                <label>ADBD</label>
            </value>
            <value>
                <fullName>ADBD/SPKR</fullName>
                <isActive>false</isActive>
                <label>ADBD/SPKR</label>
            </value>
            <value>
                <fullName>Advisory Board</fullName>
                <isActive>false</isActive>
                <label>Advisory Board</label>
            </value>
            <value>
                <fullName>GOVCOMP</fullName>
                <isActive>false</isActive>
                <label>GOVCOMP</label>
            </value>
            <value>
                <fullName>GOVPAID</fullName>
                <isActive>false</isActive>
                <label>GOVPAID</label>
            </value>
            <value>
                <fullName>Gov Attendee</fullName>
                <isActive>false</isActive>
                <label>Gov Attendee</label>
            </value>
            <value>
                <fullName>Government Attendee</fullName>
                <isActive>false</isActive>
                <label>Government Attendee</label>
            </value>
            <value>
                <fullName>Government Complimentary</fullName>
                <isActive>false</isActive>
                <label>Government Complimentary</label>
            </value>
            <value>
                <fullName>Government Paid</fullName>
                <isActive>false</isActive>
                <label>Government Paid</label>
            </value>
            <value>
                <fullName>INDCOMP</fullName>
                <isActive>false</isActive>
                <label>INDCOMP</label>
            </value>
            <value>
                <fullName>INDPAID</fullName>
                <isActive>false</isActive>
                <label>INDPAID</label>
            </value>
            <value>
                <fullName>Industry</fullName>
                <isActive>false</isActive>
                <label>Industry</label>
            </value>
            <value>
                <fullName>Industry Atendee</fullName>
                <isActive>false</isActive>
                <label>Industry Atendee</label>
            </value>
            <value>
                <fullName>Industry Complimentary</fullName>
                <isActive>false</isActive>
                <label>Industry Complimentary</label>
            </value>
            <value>
                <fullName>Industry Paid</fullName>
                <isActive>false</isActive>
                <label>Industry Paid</label>
            </value>
            <value>
                <fullName>Item Created</fullName>
                <isActive>false</isActive>
                <label>Item Created</label>
            </value>
            <value>
                <fullName>O Online</fullName>
                <isActive>false</isActive>
                <label>O Online</label>
            </value>
            <value>
                <fullName>PRES</fullName>
                <isActive>false</isActive>
                <label>PRES</label>
            </value>
            <value>
                <fullName>Private</fullName>
                <isActive>false</isActive>
                <label>Private</label>
            </value>
            <value>
                <fullName>Private Sector</fullName>
                <isActive>false</isActive>
                <label>Private Sector</label>
            </value>
            <value>
                <fullName>Public</fullName>
                <isActive>false</isActive>
                <label>Public</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Registrant_Name__c.field-meta.xml
<CustomField>
    <fullName>Registrant_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registrant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Transaction_ID__c.field-meta.xml
<CustomField>
    <fullName>Transaction_ID__c</fullName>
    <description
  >Convert this field to text once APEX &quot;eventAttendeeNotification_test&quot; has been removed from the system.</description>
    <externalId>true</externalId>
    <label>Authorize.Net ID (numeric)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/eventAttendeeNotification_test.cls
@isTest
private class eventAttendeeNotification_test {
  static testMethod void triggerTest1() {
    Events__c evt = new Events__c(
      Name = 'Test Event',
      Brand__c = 'Exec Events'
    );
    insert evt;
    Contact contact = testData.createContact();

    Registration__c reg = new Registration__c(
      Event__c = evt.Id,
      Registrant_Name__c = contact.Id,
      Transaction_ID__c = 4593659217L
    );
    insert reg;

    // the following lines are to test the 'registration' trigger
    reg.Exclude_From_Mailing_List__c = true;
    update reg;
    delete reg;
  }

  static testMethod void triggerTest2() {
    Events__c evt = new Events__c(
      Name = 'Test Event',
      Brand__c = 'Exec Events'
    );
    insert evt;
    Contact contact = testData.createContact();

    Registration__c reg = new Registration__c(
      Event__c = evt.Id,
      Registrant_Name__c = contact.Id,
      Reg_Type__c = 'Sponsor'
    );
    insert reg;
  }

  static testMethod void triggerTest3() {
    Events__c evt = new Events__c(Name = 'Test Event', Brand__c = 'EM');
    insert evt;
    Contact contact = testData.createContact();

    Registration__c reg = new Registration__c(
      Event__c = evt.Id,
      Registrant_Name__c = contact.Id,
      Reg_Type__c = 'Govt Attendee'
    );
    insert reg;
  }

  static testMethod void triggerTest4() {
    Events__c evt = new Events__c(Name = 'Test Event', Brand__c = 'EM');
    insert evt;
    Contact contact = testData.createContact();

    Registration__c reg = new Registration__c(
      Event__c = evt.Id,
      Registrant_Name__c = contact.Id,
      Reg_Type__c = 'Govt Attendee',
      Reg_Source__c = 'P Phone'
    );
    insert reg;
  }
}