force-app/main/default/objects/Events__c/Events__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >Standard_Event_Compact_Layout</compactLayoutAssignment>
    <description
  >These are e.Republic Events - tradeshows, executive events, webinars, roundtables, custom events, etc.</description>
    <label>Event or Conference</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events and Conferences</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Events__c/fields/Banner_URL__c.field-meta.xml
<CustomField>
    <fullName>Banner_URL__c</fullName>
    <label>Banner URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Display_Name__c</fullName>
    <description>This is used on the web page</description>
    <inlineHelpText>This is used on the web page</inlineHelpText>
    <label>Display Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Event_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_End_Date__c</fullName>
    <description>This is the end date of the event.</description>
    <inlineHelpText>This is the end date of the event.</inlineHelpText>
    <label>Event End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Event_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_Start_Date__c</fullName>
    <description>This is the start date of the event.</description>
    <inlineHelpText>This is the start date of the event.</inlineHelpText>
    <label>Event Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Public_Reg_Fee__c.field-meta.xml
<CustomField>
    <fullName>Public_Reg_Fee__c</fullName>
    <label>Public Registration Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Registration_Open__c.field-meta.xml
<CustomField>
    <fullName>Registration_Open__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Registration Open</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Web_Status__c.field-meta.xml
<CustomField>
    <fullName>Web_Status__c</fullName>
    <inlineHelpText
  >when status is &quot;in progress&quot; the event can be previewed at stage.www.govtech.com</inlineHelpText>
    <label>Web Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/eventSponsorshipDetailController_test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 *
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(seeAllData=true)
private class eventSponsorshipDetailController_test {
  static testMethod void myUnitTest() {
    Test.setCurrentPage(new PageReference('/apex/event_sp_report'));

    Account a = new Account(
      Name = 'e.Republic - Subscriptions',
      type = 'Customer'
    );
    insert a;

    Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];

    User u = new User(
      alias = 'u1',
      email = 'foo@test.com',
      lastname = 'Smith',
      firstname = 'John',
      username = 'testuser1@erepublic.com',
      emailencodingkey = 'UTF-8',
      languagelocalekey = 'en_US',
      localesidkey = 'en_US',
      TimeZoneSidKey = 'America/Los_Angeles',
      ProfileId = p.Id
    );
    insert u;

    Events__c evt = new Events__c(
      Name = 'Paid Event',
      Registration_Open__c = true,
      Display_Name__c = 'Paid Event',
      OwnerId = u.Id,
      Public_Reg_Fee__c = 200,
      Event_Start_Date__c = date.Today(),
      Event_End_Date__c = date.Today(),
      Banner_URL__c = 'http://www.test.com',
      Web_Status__c = 'live'
    );
    insert evt;

    ApexPages.currentPage().getParameters().put('id', evt.Id);
    eventSponsorshipDetailController controller = new eventSponsorshipDetailController();
  }
}