force-app/main/default/objects/Events__c/Events__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >Standard_Event_Compact_Layout</compactLayoutAssignment>
    <description
  >These are e.Republic Events - tradeshows, executive events, webinars, roundtables, custom events, etc.</description>
    <label>Event or Conference</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events and Conferences</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Events__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <description
  >The primary brand of the event. Event may still be listed on multiple websites.</description>
    <inlineHelpText
  >The primary brand of the event. Event may still be listed on multiple websites.</inlineHelpText>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>GOVERNING</fullName>
            </value>
            <value>
                <fullName>GOVTECH</fullName>
            </value>
            <value>
                <fullName>PCIO</fullName>
            </value>
            <value>
                <fullName>CDE</fullName>
            </value>
            <value>
                <fullName>CDG</fullName>
            </value>
            <value>
                <fullName>EMERGENCYMGMT</fullName>
            </value>
            <value>
                <fullName>EREPUBLIC</fullName>
            </value>
            <value>
                <fullName>DIGITAL_COMMUNITIES</fullName>
            </value>
            <value>
                <fullName>FUTURE_STRUCTURE</fullName>
            </value>
            <value>
                <fullName>INSIDER CA</fullName>
            </value>
            <value>
                <fullName>INSIDER TX</fullName>
            </value>
            <value>
                <fullName>INSIDER FL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Events__c/fields/Event_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_End_Date__c</fullName>
    <description>This is the end date of the event.</description>
    <inlineHelpText>This is the end date of the event.</inlineHelpText>
    <label>Event End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Event_Month__c.field-meta.xml
<CustomField>
    <fullName>Event_Month__c</fullName>
    <description
  >The month of the event as determined by Logistics.</description>
    <inlineHelpText
  >The month of the event as determined by Logistics.</inlineHelpText>
    <label>Event Month</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>January</fullName>
            </value>
            <value>
                <fullName>February</fullName>
            </value>
            <value>
                <fullName>March</fullName>
            </value>
            <value>
                <fullName>April</fullName>
            </value>
            <value>
                <fullName>May</fullName>
            </value>
            <value>
                <fullName>June</fullName>
            </value>
            <value>
                <fullName>July</fullName>
            </value>
            <value>
                <fullName>August</fullName>
            </value>
            <value>
                <fullName>September</fullName>
            </value>
            <value>
                <fullName>October</fullName>
            </value>
            <value>
                <fullName>November</fullName>
            </value>
            <value>
                <fullName>December</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Events__c/fields/Event_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_Start_Date__c</fullName>
    <description>This is the start date of the event.</description>
    <inlineHelpText>This is the start date of the event.</inlineHelpText>
    <label>Event Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Event_Year__c.field-meta.xml
<CustomField>
    <fullName>Event_Year__c</fullName>
    <description
  >Specify the year of the event for reporting purposes. [HOTS PACKET]</description>
    <inlineHelpText
  >Specify the year of the event for reporting purposes.  [HOTS PACKET]</inlineHelpText>
    <label>Event Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Ship_To_Address__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Address__c</fullName>
    <description
  >All shipments should be properly labeled as shown here.</description>
    <inlineHelpText
  >All shipments should be properly labeled as shown here.</inlineHelpText>
    <label>Ship To Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Shipping_Notes__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Notes__c</fullName>
    <description
  >Additional notes for special handling regarding shipping packages to this event.</description>
    <inlineHelpText
  >Additional notes for special handling regarding shipping packages to this event.</inlineHelpText>
    <label>Shipping Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/event_logistics_controller.cls
public class event_logistics_controller {
  // Used by event_logistics_by_year   Visual Source Page

  private Map<String, String> brand_names = new Map<String, String>{
    'EMERGENCYMGMT' => 'Emergency Management',
    'GOVTECH' => 'Government Technology',
    'GOVERNING' => 'Governing',
    'TECHWIRE' => 'TechWire',
    'CDG' => 'CDG',
    'CDE' => 'CDE'
  };

  public String brand_name { get; set; }
  public Integer year { get; set; }
  public List<LogisticsData> logistics { get; set; }

  public event_logistics_controller() {
    logistics = new List<LogisticsData>();
    year = Integer.valueOf(
      ApexPages.currentPage().getParameters().get('year').trim()
    );
    String brand = ApexPages.currentPage().getParameters().get('brand');
    brand_name = brand_names.get(brand);
    for (Events__c e : [
      SELECT
        Id,
        Name,
        Shipping_Notes__c,
        Ship_To_Address__c,
        Event_Start_Date__c,
        Event_End_Date__c,
        Event_Month__c
      FROM Events__c
      WHERE
        RecordTypeId = '01230000000ueuw'
        AND Brand__c = :brand
        AND Event_Year__c = :year
        AND (NOT Name LIKE '%REG ONLY%')
      ORDER BY Event_Month__c, Event_Start_Date__c
    ]) {
      logistics.add(new LogisticsData(e));
    }
  }

  // data container class
  class LogisticsData {
    public String name { get; set; }
    public String dates { get; set; }
    public String shipping_notes { get; set; }
    public String shipping_address { get; set; }

    public LogisticsData(Events__c e) {
      name = e.Name;
      if (e.Shipping_Notes__c != null)
        shipping_notes = '<p>' + e.Shipping_Notes__c + '</p>';
      else
        shipping_notes = '';

      if (e.Ship_To_Address__c != null)
        shipping_address =
          '<p> <b>All shipments should be properly labeled as shown below:</b> <br>' +
          e.Ship_To_Address__c +
          '</p>';
      else
        shipping_address = '';

      shipping_notes = replaceLineBreaks(shipping_notes);
      shipping_address = replaceLineBreaks(shipping_address);

      if (e.Event_Start_Date__c == null) {
        if (e.Event_Month__c == null)
          dates = '';
        else
          dates = e.Event_Month__c;
      } else {
        DateTime sd = e.Event_Start_Date__c;
        DateTime ed = e.Event_End_Date__c;

        // it looks like the dates are put in as GMT person entering must be on GMT
        dates = sd.format('MMM d', 'GMT');
        if (e.Event_End_Date__c != null && ed.dayOfYear() != sd.dayOfYear()) {
          if (ed.month() != sd.month())
            dates += ed.format(' - MMM d', 'GMT');
          else
            dates += ed.format(' - d', 'GMT');
        }
      } //e.Event_Start_Date__c != null
    }

    String replaceLineBreaks(String str) {
      str = str.replaceAll('\r\n', '<br/>');
      str = str.replaceAll('\n', '<br/>');
      str = str.replaceAll('\r', '<br/>');
      return str;
    }
  } // end off class LogisticsData
}