force-app/main/default/objects/Events__c/Events__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >Standard_Event_Compact_Layout</compactLayoutAssignment>
    <description
  >These are e.Republic Events - tradeshows, executive events, webinars, roundtables, custom events, etc.</description>
    <label>Event or Conference</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events and Conferences</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/QR_Scan__c/QR_Scan__c.object-meta.xml
<CustomObject>
    <description
  >An instance of a QR code scanned from the native e.Badger app.</description>
    <label>QR Scan</label>
    <nameField>
        <label>QR Scan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QR Scans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QR_Scan__c/fields/App_Scan_ID__c.field-meta.xml
<CustomField>
    <fullName>App_Scan_ID__c</fullName>
    <description>Internal ID for apps to identify scans</description>
    <label>App Scan ID</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QR_Scan__c/fields/Data_Scanned__c.field-meta.xml
<CustomField>
    <fullName>Data_Scanned__c</fullName>
    <description>What was actually decoded from the QR code</description>
    <label>Data Scanned</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/QR_Scan__c/fields/Event_or_Conference__c.field-meta.xml
<CustomField>
    <fullName>Event_or_Conference__c</fullName>
    <label>Event or Conference</label>
    <referenceTo>Events__c</referenceTo>
    <relationshipLabel>QR Scans</relationshipLabel>
    <relationshipName>QR_Scans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QR_Scan__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/QR_Scan__c/fields/Scan_Intent__c.field-meta.xml
<CustomField>
    <fullName>Scan_Intent__c</fullName>
    <description
  >Based on the state of the badge scanning app, this will denote the intention of the person scanning the badge.</description>
    <label>Scan Intent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Registration Check-In</fullName>
            </value>
            <value>
                <fullName>Session Attendance</fullName>
            </value>
            <value>
                <fullName>Registration Mark No-Show</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QR_Scan__c/fields/Scanned__c.field-meta.xml
<CustomField>
    <fullName>Scanned__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The person who was scanned</description>
    <label>Scanned</label>
    <referenceTo>Registration__c</referenceTo>
    <relationshipLabel>QR Scans</relationshipLabel>
    <relationshipName>QR_Scans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QR_Scan__c/fields/Scanner__c.field-meta.xml
<CustomField>
    <fullName>Scanner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The person doing the scanning</description>
    <label>Scanner</label>
    <referenceTo>Registration__c</referenceTo>
    <relationshipLabel>QR Scans (Scanner)</relationshipLabel>
    <relationshipName>QR_Scans1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QR_Scan__c/fields/Tmp_Scanner_Id__c.field-meta.xml
<CustomField>
    <fullName>Tmp_Scanner_Id__c</fullName>
    <label>Tmp Scanner Id</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QR_Code_Trigger_test.cls
@isTest(SeeAllData=true)
public class QR_Code_Trigger_test {
  static testMethod void testNewFormat() {
    QR_Scan__c qrc4 = new QR_Scan__c(
      App_Scan_ID__c = 12353,
      Data_Scanned__c = '//_T1234567890AB/Clinton Bill',
      Tmp_Scanner_Id__c = '_T1234567888CC',
      Notes__c = ' Nice guy!',
      Scan_Intent__c = 'General',
      Event_or_Conference__c = 'a0m14000007u0JlAAI'
    );
    insert qrc4;
    // new scan with real reg id.
    QR_Scan__c qrc5 = new QR_Scan__c(
      App_Scan_ID__c = 12354,
      Data_Scanned__c = '//a0l1O00000F2KbK/Williams Tim',
      Tmp_Scanner_Id__c = 'a0l1O00000F2HK6',
      Notes__c = 'Why did they let developers in?',
      Scan_Intent__c = 'General',
      Event_or_Conference__c = 'a0m1O000008hQxO'
    );
    insert qrc5;
    // the registrations that are created with the event will have TMPORARY_ID '_T1234567888CC' and '_T1234567890AB'
    Events__c event = testdata.createEventWithRegistrations();

    QR_Scan__c qrc3 = new QR_Scan__c(
      App_Scan_ID__c = 12355,
      Data_Scanned__c = '//_T1234567888CC/Jackson Joe',
      Tmp_Scanner_Id__c = '_T1234567890AB',
      Event_or_Conference__c = event.Id
    );
    insert qrc3;
  }

  static testMethod void testDuplicateQRInsert() {
    // testing old style
    QR_Scan__c qrc = new QR_Scan__c(
      Scanned__c = 'a0l1O00000Eq36UQAR',
      Scanner__c = 'a0l1O00000EqG3eQAF',
      Event_or_Conference__c = 'a0m14000007u0JlAAI'
    );
    insert qrc;

    QR_Scan__c qrc2 = new QR_Scan__c(
      Scanned__c = 'a0l1O00000Eq36UQAR',
      Scanner__c = 'a0l1O00000EqG3eQAF',
      Event_or_Conference__c = 'a0m14000007u0JlAAI'
    );

    try {
      insert qrc2;
      System.assert(false, 'duplicate scan insert not prevented');
    } catch (Exception e) {
      System.assert(
        e.getMessage().contains('duplicate scan insert prevented'),
        true
      );
    }

    QR_Scan__c qrc3 = new QR_Scan__c(
      App_Scan_ID__c = 12355,
      Data_Scanned__c = '//_T1234567888CC/Jackson Joe',
      Tmp_Scanner_Id__c = '_T1234567890AB',
      Event_or_Conference__c = 'a0m14000007u0JlAAI'
    );
    insert qrc3;

    QR_Scan__c qrc4 = new QR_Scan__c(
      App_Scan_ID__c = 12355,
      Data_Scanned__c = '//_T1234567888CC/Jackson Joe',
      Tmp_Scanner_Id__c = '_T1234567890AB',
      Event_or_Conference__c = 'a0m14000007u0JlAAI'
    );
    try {
      insert qrc4;
      System.assert(false, 'duplicate scan insert not prevented');
    } catch (Exception e) {
      System.assert(
        e.getMessage().contains('duplicate scan insert prevented'),
        true
      );
    }
  }
}