force-app/main/default/objects/Events__c/Events__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >Standard_Event_Compact_Layout</compactLayoutAssignment>
    <description
  >These are e.Republic Events - tradeshows, executive events, webinars, roundtables, custom events, etc.</description>
    <label>Event or Conference</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events and Conferences</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Events__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <description
  >The primary brand of the event. Event may still be listed on multiple websites.</description>
    <inlineHelpText
  >The primary brand of the event. Event may still be listed on multiple websites.</inlineHelpText>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>GOVERNING</fullName>
            </value>
            <value>
                <fullName>GOVTECH</fullName>
            </value>
            <value>
                <fullName>PCIO</fullName>
            </value>
            <value>
                <fullName>CDE</fullName>
            </value>
            <value>
                <fullName>CDG</fullName>
            </value>
            <value>
                <fullName>EMERGENCYMGMT</fullName>
            </value>
            <value>
                <fullName>EREPUBLIC</fullName>
            </value>
            <value>
                <fullName>DIGITAL_COMMUNITIES</fullName>
            </value>
            <value>
                <fullName>FUTURE_STRUCTURE</fullName>
            </value>
            <value>
                <fullName>INSIDER CA</fullName>
            </value>
            <value>
                <fullName>INSIDER TX</fullName>
            </value>
            <value>
                <fullName>INSIDER FL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Events__c/fields/Event_Quarter__c.field-meta.xml
<CustomField>
    <fullName>Event_Quarter__c</fullName>
    <description
  >This is the quarter of the year in which the event will take place.</description>
    <inlineHelpText
  >This is the quarter of the year in which the event will take place.</inlineHelpText>
    <label>Event Quarter</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Q1</fullName>
            </value>
            <value>
                <fullName>Q2</fullName>
            </value>
            <value>
                <fullName>Q3</fullName>
            </value>
            <value>
                <fullName>Q4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Events__c/fields/Event_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_Start_Date__c</fullName>
    <description>This is the start date of the event.</description>
    <inlineHelpText>This is the start date of the event.</inlineHelpText>
    <label>Event Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <description>The type/format of the event.</description>
    <inlineHelpText>The type/format of the event.</inlineHelpText>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CDG Event</fullName>
            </value>
            <value>
                <fullName>Custom_Event</fullName>
            </value>
            <value>
                <fullName>Custom_Event w/ Website</fullName>
            </value>
            <value>
                <fullName>Custom_Roundtable</fullName>
            </value>
            <value>
                <fullName>Custom_Webinar</fullName>
            </value>
            <value>
                <fullName>EM Events</fullName>
            </value>
            <value>
                <fullName>Exec Event</fullName>
            </value>
            <value>
                <fullName>Podcast</fullName>
            </value>
            <value>
                <fullName>Registration only</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
            <value>
                <fullName>Custom Roundtable</fullName>
            </value>
            <value>
                <fullName>Solution Series</fullName>
            </value>
            <value>
                <fullName>Standard_Invitation only</fullName>
            </value>
            <value>
                <fullName>Standard_Invitation only - no website</fullName>
            </value>
            <value>
                <fullName>Standard_Invitation only w/ Hub</fullName>
            </value>
            <value>
                <fullName>Standard_Members Only</fullName>
            </value>
            <value>
                <fullName>Standard_Private and Public Sector</fullName>
            </value>
            <value>
                <fullName
        >Standard_Private and Public Sector - no website</fullName>
                <label>Standard_Private and Public Sector - no website</label>
            </value>
            <value>
                <fullName>Standard_Program</fullName>
            </value>
            <value>
                <fullName>Standard_Program - no website</fullName>
            </value>
            <value>
                <fullName>Standard_Program_Custom Event</fullName>
            </value>
            <value>
                <fullName>Standard_Program_Custom Event w/ Website</fullName>
            </value>
            <value>
                <fullName>Standard_Program_Invitation only</fullName>
            </value>
            <value>
                <fullName>Standard_Program_Invitation only_no website</fullName>
            </value>
            <value>
                <fullName>Standard_Program_Public Sector only</fullName>
            </value>
            <value>
                <fullName>Standard_Public Sector only</fullName>
            </value>
            <value>
                <fullName>Standard_Public Sector only - no website</fullName>
            </value>
            <value>
                <fullName>Standard_Public Sector only w/ Hub</fullName>
            </value>
            <value>
                <fullName
        >Standard_Teleconference_Marketing - no website</fullName>
                <label>Standard_Teleconference_Marketing - no website</label>
            </value>
            <value>
                <fullName>Standard_Teleconference - no website</fullName>
            </value>
            <value>
                <fullName>Standard_Test Event</fullName>
            </value>
            <value>
                <fullName>Standard_Webinar_Marketing - no website</fullName>
            </value>
            <value>
                <fullName>Standard_Webinar_Program - no website</fullName>
            </value>
            <value>
                <fullName>Unconference</fullName>
            </value>
            <value>
                <fullName>Lunch &amp; Learn Webinar</fullName>
            </value>
            <value>
                <fullName>State Editorial Roundtable</fullName>
            </value>
            <value>
                <fullName>State-Specific Webinar</fullName>
            </value>
            <value>
                <fullName>Webinar</fullName>
            </value>
            <value>
                <fullName>Virtual Conversation</fullName>
            </value>
            <value>
                <fullName>Virtual Meeting</fullName>
            </value>
            <value>
                <fullName>Virtual Summit</fullName>
            </value>
            <value>
                <fullName>Account Based Marketing</fullName>
            </value>
            <value>
                <fullName>Multi-Touch Nurture</fullName>
            </value>
            <value>
                <fullName>Two Step Nurture</fullName>
            </value>
            <value>
                <fullName>Filtered Leads</fullName>
            </value>
            <value>
                <fullName>Standard Leads</fullName>
            </value>
            <value>
                <fullName>Standard_Program_Custom Roundtable</fullName>
            </value>
            <value>
                <fullName>Standard_Program_Webinar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Events__c/fields/Event_Year__c.field-meta.xml
<CustomField>
    <fullName>Event_Year__c</fullName>
    <description
  >Specify the year of the event for reporting purposes. [HOTS PACKET]</description>
    <inlineHelpText
  >Specify the year of the event for reporting purposes.  [HOTS PACKET]</inlineHelpText>
    <label>Event Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/eventSponsorshipController.cls
public class eventSponsorshipController { // test method for this class can be found in eventSponsorship_test
  public String Brand { get; set; }
  public List<QuarterListing> Quarters { get; set; }

  public eventSponsorshipController() {
    Quarters = new List<QuarterListing>();
    Date startDate;
    Date endDate;
    Integer startMonth;
    Integer endMonth;
    Integer year;
    Integer monthsInQuarter = 3;
    Integer quarter_num;

    Brand = ApexPages.currentPage().getParameters().get('brand');

    List<Events__c> tmp_list;

    // Start with beginning of this year, end with end of next year
    for (Integer i = 0; i < 8; i++) {
      //startMonth = (i * monthsInQuarter) + 1;
      //endMonth = startMonth + monthsInQuarter;
      if (i < 4) {
        year = date.today().year();
      } else {
        year = date.today().year() + 1;
      }

      if (i >= 4) {
        quarter_num = (i + 1) - 4;
      } else {
        quarter_num = (i + 1);
      }

      //startDate = date.newInstance(year, startMonth, 1);
      //endDate = date.newInstance(year, endMonth, 1);
      //System.debug(startDate + ' - ' + endDate);

      tmp_list = getEvents(quarter_num, year);

      if (tmp_list.size() > 0) {
        Quarters.add(new QuarterListing(quarter_num, year, tmp_list));
      }
    }
  }

  @TestVisible
  public class QuarterListing {
    public String title { get; set; }
    public List<Events__c> events { get; set; }
    public Integer Quarter { get; set; }
    public Integer Year { get; set; }

    // Quarter and year should be revisted.
    @TestVisible
    QuarterListing(Integer q, Integer y, List<Events__c> e) {
      title = 'Quarter ' + q + ', ' + y;
      events = e;
      Quarter = q;
      Year = y;
    }
  }

  public List<Events__c> getEvents(Integer quarter, Integer year) {
    String theQuarter = 'Q' + String.valueOf(quarter);
    return [
      SELECT Id, Name, Event_Start_Date__c
      FROM Events__c
      WHERE
        Event_Quarter__c = :theQuarter
        AND Event_Year__c = :year
        AND Brand__c = :Brand
        AND Event_Type__c = 'Virtual Summit'
        AND RecordTypeId IN (
          SELECT Id
          FROM RecordType
          WHERE Name = 'Standard Event'
        )
      ORDER BY Event_Start_Date__c
    ];
  }
}