force-app/main/default/objects/Events__c/Events__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >Standard_Event_Compact_Layout</compactLayoutAssignment>
    <description
  >These are e.Republic Events - tradeshows, executive events, webinars, roundtables, custom events, etc.</description>
    <label>Event or Conference</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events and Conferences</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Events__c/fields/Duration_minutes__c.field-meta.xml
<CustomField>
    <fullName>Duration_minutes__c</fullName>
    <description
  >The duration, in minutes, of the webinar. Must be set in OneForm.</description>
    <inlineHelpText
  >The duration, in minutes, of the webinar. Must be set in OneForm.</inlineHelpText>
    <label>Duration (minutes)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>45</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>75</fullName>
            </value>
            <value>
                <fullName>90</fullName>
            </value>
            <value>
                <fullName>120</fullName>
            </value>
            <value>
                <fullName>150</fullName>
            </value>
            <value>
                <fullName>180</fullName>
            </value>
            <value>
                <fullName>210</fullName>
            </value>
            <value>
                <fullName>240</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Events__c/fields/Replace_ADBD_with_Planning_Committee__c.field-meta.xml
<CustomField>
    <fullName>Replace_ADBD_with_Planning_Committee__c</fullName>
    <defaultValue>false</defaultValue>
    <description
  >Syncs to CMS and ERMS to replace the Advisory Board Language on the Event Website and Registrant Badges with “Planning Committee”.</description>
    <inlineHelpText
  >Replaces “Advisory Board” language on the Event Website and Registrants’ Badges with “Planning Committee”.</inlineHelpText>
    <label>Replace ADBD with Planning Committee</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Events__c/recordTypes/Custom_Event.recordType-meta.xml
<RecordType>
    <fullName>Custom_Event</fullName>
    <active>true</active>
    <compactLayoutAssignment
  >Standard_Event_Compact_Layout</compactLayoutAssignment>
    <description
  >Custom Contracted Event or Event Series, usually with a Single Topic &amp; Sponsor (Roadshow, Editorial Roundtable, etc.)</description>
    <label>Custom Event</label>
</RecordType>

force-app/main/default/objects/Events__c/recordTypes/Webinar.recordType-meta.xml
<RecordType>
    <fullName>Webinar</fullName>
    <active>true</active>
    <compactLayoutAssignment
  >Standard_Event_Compact_Layout</compactLayoutAssignment>
    <description>Webinars, Teleconferences, Online Forum Events</description>
    <label>Webinar</label>
</RecordType>

force-app/main/default/classes/events_test.cls
@isTest
private class events_test {
  static testMethod void myUnitTest() {
    Test.startTest();
    System.debug('Test 1 Standard event on create');
    Events__c event = testData.createEvent(true);
    //event.name = 'testing';
    event.Replace_ADBD_with_Planning_Committee__c = true;
    System.debug('Test 2 Standard event on update');
    update event;
    try {
      System.debug('Test 3 Standard event on delete');
      delete event; // Expected DMLException
    } catch (DmlException e) {
      // Assert that the expected error is thrown
      System.assertEquals(
        e.getMessage().contains('Only CmsAdmin can delete events'),
        true,
        'Error message not found'
      );
    }
    System.debug('Test 4 Standard event on create');
    Events__c custom_event = testData.createEvent(true);
    custom_event.RecordTypeId = testData.RECORD_TYPE_CUSTOM_EVENT;
    custom_event.name = 'custom event!';
    System.debug('Test 5 Custom event on update');
    update custom_event;

    System.debug('Test 6 Standard event on create');
    Events__c webinar = testData.createEvent(true);
    webinar.RecordTypeId = testData.RECORD_TYPE_WEBINAR;
    webinar.Duration_minutes__c = '60';
    System.debug('Test 7 webinar event on update');
    update webinar;
    //delete webinar;

    Test.stopTest();
  }
}