force-app/main/default/objects/Events__c/Events__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >Standard_Event_Compact_Layout</compactLayoutAssignment>
    <description
  >These are e.Republic Events - tradeshows, executive events, webinars, roundtables, custom events, etc.</description>
    <label>Event or Conference</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events and Conferences</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Events__c/fields/Banner_URL__c.field-meta.xml
<CustomField>
    <fullName>Banner_URL__c</fullName>
    <label>Banner URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <description
  >The primary brand of the event. Event may still be listed on multiple websites.</description>
    <inlineHelpText
  >The primary brand of the event. Event may still be listed on multiple websites.</inlineHelpText>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>GOVERNING</fullName>
            </value>
            <value>
                <fullName>GOVTECH</fullName>
            </value>
            <value>
                <fullName>PCIO</fullName>
            </value>
            <value>
                <fullName>CDE</fullName>
            </value>
            <value>
                <fullName>CDG</fullName>
            </value>
            <value>
                <fullName>EMERGENCYMGMT</fullName>
            </value>
            <value>
                <fullName>EREPUBLIC</fullName>
            </value>
            <value>
                <fullName>DIGITAL_COMMUNITIES</fullName>
            </value>
            <value>
                <fullName>FUTURE_STRUCTURE</fullName>
            </value>
            <value>
                <fullName>INSIDER CA</fullName>
            </value>
            <value>
                <fullName>INSIDER TX</fullName>
            </value>
            <value>
                <fullName>INSIDER FL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Events__c/fields/Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Display_Name__c</fullName>
    <description>This is used on the web page</description>
    <inlineHelpText>This is used on the web page</inlineHelpText>
    <label>Display Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Event_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_End_Date__c</fullName>
    <description>This is the end date of the event.</description>
    <inlineHelpText>This is the end date of the event.</inlineHelpText>
    <label>Event End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Event_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_Start_Date__c</fullName>
    <description>This is the start date of the event.</description>
    <inlineHelpText>This is the start date of the event.</inlineHelpText>
    <label>Event Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Public_Reg_Fee__c.field-meta.xml
<CustomField>
    <fullName>Public_Reg_Fee__c</fullName>
    <label>Public Registration Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Venue_State__c.field-meta.xml
<CustomField>
    <fullName>Venue_State__c</fullName>
    <label>Venue State</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Web_Status__c.field-meta.xml
<CustomField>
    <fullName>Web_Status__c</fullName>
    <inlineHelpText
  >when status is &quot;in progress&quot; the event can be previewed at stage.www.govtech.com</inlineHelpText>
    <label>Web Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >Registration_Compact_Layout</compactLayoutAssignment>
    <description
  >This is a registration for any event, conference, forum, webinar, etc. across all e.Republic business units.</description>
    <label>Registration</label>
    <nameField>
        <displayFormat>REG-{000000}</displayFormat>
        <label>Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <formula>Text ( Event__r.Brand__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Brand</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Events__c</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Event_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_Start_Date__c</fullName>
    <description
  >Created for Ticket #81193 to allow sorting on related record component on Privacy Request records.</description>
    <formula>Event__r.Event_Start_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Event Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Reg_Date__c.field-meta.xml
<CustomField>
    <fullName>Reg_Date__c</fullName>
    <label>Reg Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Reg_Type__c.field-meta.xml
<CustomField>
    <fullName>Reg_Type__c</fullName>
    <inlineHelpText
  >Enter the type of registration i.e. Sponsor, Speaker, etc.</inlineHelpText>
    <label>Reg Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Association</fullName>
            </value>
            <value>
                <fullName>Govt Attendee</fullName>
                <default>true</default>
                <label>Govt Attendee</label>
            </value>
            <value>
                <fullName>Industry Attendee</fullName>
            </value>
            <value>
                <fullName>Sponsor</fullName>
            </value>
            <value>
                <fullName>Press</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>1</fullName>
                <isActive>false</isActive>
                <label>1</label>
            </value>
            <value>
                <fullName>ABSPON</fullName>
                <isActive>false</isActive>
                <label>ABSPON</label>
            </value>
            <value>
                <fullName>ADBD</fullName>
                <isActive>false</isActive>
                <label>ADBD</label>
            </value>
            <value>
                <fullName>ADBD/SPKR</fullName>
                <isActive>false</isActive>
                <label>ADBD/SPKR</label>
            </value>
            <value>
                <fullName>Advisory Board</fullName>
                <isActive>false</isActive>
                <label>Advisory Board</label>
            </value>
            <value>
                <fullName>GOVCOMP</fullName>
                <isActive>false</isActive>
                <label>GOVCOMP</label>
            </value>
            <value>
                <fullName>GOVPAID</fullName>
                <isActive>false</isActive>
                <label>GOVPAID</label>
            </value>
            <value>
                <fullName>Gov Attendee</fullName>
                <isActive>false</isActive>
                <label>Gov Attendee</label>
            </value>
            <value>
                <fullName>Government Attendee</fullName>
                <isActive>false</isActive>
                <label>Government Attendee</label>
            </value>
            <value>
                <fullName>Government Complimentary</fullName>
                <isActive>false</isActive>
                <label>Government Complimentary</label>
            </value>
            <value>
                <fullName>Government Paid</fullName>
                <isActive>false</isActive>
                <label>Government Paid</label>
            </value>
            <value>
                <fullName>INDCOMP</fullName>
                <isActive>false</isActive>
                <label>INDCOMP</label>
            </value>
            <value>
                <fullName>INDPAID</fullName>
                <isActive>false</isActive>
                <label>INDPAID</label>
            </value>
            <value>
                <fullName>Industry</fullName>
                <isActive>false</isActive>
                <label>Industry</label>
            </value>
            <value>
                <fullName>Industry Atendee</fullName>
                <isActive>false</isActive>
                <label>Industry Atendee</label>
            </value>
            <value>
                <fullName>Industry Complimentary</fullName>
                <isActive>false</isActive>
                <label>Industry Complimentary</label>
            </value>
            <value>
                <fullName>Industry Paid</fullName>
                <isActive>false</isActive>
                <label>Industry Paid</label>
            </value>
            <value>
                <fullName>Item Created</fullName>
                <isActive>false</isActive>
                <label>Item Created</label>
            </value>
            <value>
                <fullName>O Online</fullName>
                <isActive>false</isActive>
                <label>O Online</label>
            </value>
            <value>
                <fullName>PRES</fullName>
                <isActive>false</isActive>
                <label>PRES</label>
            </value>
            <value>
                <fullName>Private</fullName>
                <isActive>false</isActive>
                <label>Private</label>
            </value>
            <value>
                <fullName>Private Sector</fullName>
                <isActive>false</isActive>
                <label>Private Sector</label>
            </value>
            <value>
                <fullName>Public</fullName>
                <isActive>false</isActive>
                <label>Public</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Registrant_Name__c.field-meta.xml
<CustomField>
    <fullName>Registrant_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registrant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/registrationContactUpdate_test.cls
@isTest
private class registrationContactUpdate_test {
  static testMethod void myUnitTest() {
    Account a = new Account(
      Name = 'e.Republic - Subscriptions',
      type = 'Customer'
    );
    insert a;

    Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];

    User u = new User(
      alias = 'u1',
      email = 'foo@test.com',
      lastname = 'Smith',
      firstname = 'John',
      username = 'testuser1@erepublic.com',
      emailencodingkey = 'UTF-8',
      languagelocalekey = 'en_US',
      localesidkey = 'en_US',
      TimeZoneSidKey = 'America/Los_Angeles',
      ProfileId = p.Id
    );
    insert u;

    Events__c event = new Events__c(
      Brand__c = 'CDE',
      Name = 'Paid Event',
      Display_Name__c = 'Paid Event',
      OwnerId = u.Id,
      Public_Reg_Fee__c = 200,
      Event_Start_Date__c = date.Today(),
      Event_End_Date__c = date.Today(),
      Banner_URL__c = 'http://www.test.com',
      Web_Status__c = 'live',
      Venue_State__c = 'CA'
    );
    insert event;

    Contact contact = testData.createContact();

    Registration__c reg = new Registration__c(
      Registrant_Name__c = contact.Id,
      Event__c = event.Id,
      Reg_Type__c = 'Govt Attendee',
      Reg_Date__c = date.Today(),
      Reg_Source__c = 'O Online'
    );
    insert reg;

    Contact c2 = [
      SELECT EE_Tracking_Interested__c, EE_Tracking_Past_Participant__c
      FROM Contact
      WHERE Id = :contact.Id
    ];

    System.assert(c2.EE_Tracking_Interested__c == 'CA');
    System.assert(c2.EE_Tracking_Past_Participant__c == 'CA');
  }

  static testMethod void contactWithValuesTest() {
    Account a = new Account(
      Name = 'e.Republic - Subscriptions',
      type = 'Customer'
    );
    insert a;

    Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];

    User u = new User(
      alias = 'u1',
      email = 'foo@test.com',
      lastname = 'Smith',
      firstname = 'John',
      username = 'testuser1@erepublic.com',
      emailencodingkey = 'UTF-8',
      languagelocalekey = 'en_US',
      localesidkey = 'en_US',
      TimeZoneSidKey = 'America/Los_Angeles',
      ProfileId = p.Id
    );
    insert u;

    Events__c event = new Events__c(
      Brand__c = 'GOVERNING',
      Name = 'Paid Event',
      Display_Name__c = 'Paid Event',
      OwnerId = u.Id,
      Public_Reg_Fee__c = 200,
      Event_Start_Date__c = date.Today(),
      Event_End_Date__c = date.Today(),
      Banner_URL__c = 'http://www.test.com',
      Web_Status__c = 'live',
      Venue_State__c = 'CA'
    );
    insert event;

    Contact contact = testData.createContact(false);
    contact.EE_Tracking_Interested__c = 'Test';
    contact.EE_Tracking_Past_Participant__c = 'Test';
    insert contact;

    Registration__c reg = new Registration__c(
      Registrant_Name__c = contact.Id,
      Event__c = event.Id,
      Reg_Type__c = 'Govt Attendee',
      Reg_Date__c = date.Today(),
      Reg_Source__c = 'O Online'
    );
    insert reg;

    Contact c2 = [
      SELECT EE_Tracking_Interested__c, EE_Tracking_Past_Participant__c
      FROM Contact
      WHERE Id = :contact.Id
    ];

    System.assert(c2.EE_Tracking_Interested__c == 'CA;Test');
    System.assert(c2.EE_Tracking_Past_Participant__c == 'CA;Test');
  }
}