force-app/main/default/objects/Events__c/Events__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >Standard_Event_Compact_Layout</compactLayoutAssignment>
    <description
  >These are e.Republic Events - tradeshows, executive events, webinars, roundtables, custom events, etc.</description>
    <label>Event or Conference</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events and Conferences</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Events__c/fields/Advisory_Board_1__c.field-meta.xml
<CustomField>
    <fullName>Advisory_Board_1__c</fullName>
    <description
  >The date of the first Advisory Board meeting for this event</description>
    <inlineHelpText
  >The date of the first Advisory Board meeting for this event</inlineHelpText>
    <label>Advisory Board #1</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Advisory_Board_2__c.field-meta.xml
<CustomField>
    <fullName>Advisory_Board_2__c</fullName>
    <description
  >The date of the second Advisory Board meeting for this event</description>
    <inlineHelpText
  >The date of the second Advisory Board meeting for this event</inlineHelpText>
    <label>Advisory Board #2</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Event_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_End_Date__c</fullName>
    <description>This is the end date of the event.</description>
    <inlineHelpText>This is the end date of the event.</inlineHelpText>
    <label>Event End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Event_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_Start_Date__c</fullName>
    <description>This is the start date of the event.</description>
    <inlineHelpText>This is the start date of the event.</inlineHelpText>
    <label>Event Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Event_Year__c.field-meta.xml
<CustomField>
    <fullName>Event_Year__c</fullName>
    <description
  >Specify the year of the event for reporting purposes. [HOTS PACKET]</description>
    <inlineHelpText
  >Specify the year of the event for reporting purposes.  [HOTS PACKET]</inlineHelpText>
    <label>Event Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/last_years_event__c.field-meta.xml
<CustomField>
    <fullName>last_years_event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Last Years Event</label>
    <referenceTo>Events__c</referenceTo>
    <relationshipName>Events_and_Conferences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Nickname__c.field-meta.xml
<CustomField>
    <fullName>Nickname__c</fullName>
    <description
  >This is a short version of the event&apos;s name used for reporting purposes.</description>
    <inlineHelpText
  >This is a short version of the event&apos;s name used for reporting purposes.</inlineHelpText>
    <label>Nickname</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Program_Guide_Sponsor_Deadline__c.field-meta.xml
<CustomField>
    <fullName>Program_Guide_Sponsor_Deadline__c</fullName>
    <description
  >Program Guide Sponsor Deadline (profile and logo; sponsor ads)</description>
    <inlineHelpText
  >Program Guide Sponsor Deadline (profile and logo; sponsor ads)</inlineHelpText>
    <label>Pgm Guide or SAG Sponsor Deadline EOD</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Sponsorship_Revenue_Target__c.field-meta.xml
<CustomField>
    <fullName>Sponsorship_Revenue_Target__c</fullName>
    <label>Sponsorship Revenue Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/eventSponsorshipDetailController.cls
public with sharing class eventSponsorshipDetailController {
  public eventHotSheet HotSheet { get; set; }

  public eventSponsorshipDetailController() {
    Events__c event = [
      SELECT
        Id,
        Name,
        Nickname__c,
        Event_Start_Date__c,
        Event_End_Date__c,
        Event_Year__c,
        Sponsorship_Revenue_Target__c,
        last_years_event__r.Id,
        last_years_event__r.Name,
        last_years_event__r.Nickname__c,
        last_years_event__r.Event_Start_Date__c,
        last_years_event__r.Event_End_Date__c,
        Advisory_Board_1__c,
        Advisory_Board_2__c,
        Program_Guide_Sponsor_Deadline__c
      FROM Events__c
      WHERE Id = :ApexPages.currentPage().getParameters().get('id')
    ];
    HotSheet = new eventHotSheet(event);
  }
}