force-app/main/default/objects/Events__c/Events__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >Standard_Event_Compact_Layout</compactLayoutAssignment>
    <description
  >These are e.Republic Events - tradeshows, executive events, webinars, roundtables, custom events, etc.</description>
    <label>Event or Conference</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events and Conferences</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Events__c/fields/Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Display_Name__c</fullName>
    <description>This is used on the web page</description>
    <inlineHelpText>This is used on the web page</inlineHelpText>
    <label>Display Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Event_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_End_Date__c</fullName>
    <description>This is the end date of the event.</description>
    <inlineHelpText>This is the end date of the event.</inlineHelpText>
    <label>Event End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Event_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_Start_Date__c</fullName>
    <description>This is the start date of the event.</description>
    <inlineHelpText>This is the start date of the event.</inlineHelpText>
    <label>Event Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Nickname__c.field-meta.xml
<CustomField>
    <fullName>Nickname__c</fullName>
    <description
  >This is a short version of the event&apos;s name used for reporting purposes.</description>
    <inlineHelpText
  >This is a short version of the event&apos;s name used for reporting purposes.</inlineHelpText>
    <label>Nickname</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Parent_Event__c.field-meta.xml
<CustomField>
    <fullName>Parent_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description
  >The parent event for this reception, or other child.</description>
    <inlineHelpText
  >The parent event for this reception, or other child.</inlineHelpText>
    <label>Parent Event</label>
    <referenceTo>Events__c</referenceTo>
    <relationshipLabel>Related or Sub-Events</relationshipLabel>
    <relationshipName>Sub_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Event_Additional_Products_Test.cls
@isTest(SeeAllData=true)
public class Event_Additional_Products_Test {
  static testMethod void dummy() {
  }
  /*
	static testMethod void testCreateEventAndReception() {
    	Test.startTest();
        
        // create event.
    	Events__c masterEvent = testData.createEvent(false);
        masterEvent.Nickname__c = 'ME - Nck';
        masterEvent.Name = 'Master Event';
        insert masterEvent; 
        
        // expect that an additional pass pricing record has been created
        Product2 adlPassProd = [SELECT Id,
                                Name, 
                                Display_Name__c, 
                                EE_Event__c, 
                                Product_Type__c, 
                                IsActive, 
                                CanUseRevenueSchedule,
                               	Sponsorship__c,
                                Family
                                FROM Product2
                               	WHERE EE_Event__c = :masterEvent.id
                               	AND Sponsorship__c = 'Additional Pass'];
        // test for standard values.
        System.assertEquals(masterEvent.Name+' - Additional Pass', adlPassProd.Display_Name__c);
        System.assertEquals(masterEvent.Name+' - Additional Pass', adlPassProd.Name);
        System.assertEquals(masterEvent.Id, adlPassProd.EE_Event__c);
        System.assertEquals('EE', adlPassProd.Family);
        System.assertEquals(true, adlPassProd.CanUseRevenueSchedule);
        System.assertEquals('Additional Pass', adlPassProd.Sponsorship__c);
        
        PricebookEntry pbe = [SELECT Product2ID, 
                              Pricebook2ID, 
                              UnitPrice
                              FROM PricebookEntry 
                              WHERE Product2ID = :adlPassProd.Id];
        System.assertEquals(adlPassProd.Id, pbe.Product2ID);
        System.assertEquals(500, pbe.UnitPrice);
        
        // create reception event.
    	Events__c receptionEvent = testData.createEvent(false);
        receptionEvent.Nickname__c = 'ME - NN RC YO';
        receptionEvent.Name = 'Master Event Reception';
        receptionEvent.Parent_Event__c = masterEvent.id;
        insert receptionEvent;
        
        // expect that an additional pass pricing record has been created
        Product2 adlPassProd2 = [SELECT Id,
                                Name, 
                                Display_Name__c, 
                                EE_Event__c, 
                                Product_Type__c, 
                                IsActive, 
                                CanUseRevenueSchedule,
                               	Sponsorship__c,
                                Family
                                FROM Product2
                               	WHERE EE_Event__c = :masterEvent.id
                               	AND Sponsorship__c = 'Additional Reception Pass'];
        // test for standard values.
        System.assertEquals(masterEvent.Name+' - Additional Reception Pass', adlPassProd2.Display_Name__c);
        System.assertEquals(masterEvent.Name+' - Additional Reception Pass', adlPassProd2.Name);
        System.assertEquals(masterEvent.Id, adlPassProd2.EE_Event__c);
        System.assertEquals('EE', adlPassProd2.Family);
        System.assertEquals(true, adlPassProd2.CanUseRevenueSchedule);
        System.assertEquals('Additional Reception Pass', adlPassProd2.Sponsorship__c);
        
        PricebookEntry pbe2 = [SELECT Product2ID, 
                              Pricebook2ID, 
                              UnitPrice
                              FROM PricebookEntry 
                              WHERE Product2ID = :adlPassProd2.Id];
        System.assertEquals(adlPassProd2.Id, pbe2.Product2ID);
        System.assertEquals(500, pbe2.UnitPrice);
        
    	Test.stopTest();
    }
    
    static testMethod void testNameException() {
    	Test.startTest();
        // create event with the 'REG ONLY' flag.
    	Events__c masterEvent = testData.createEvent(false);
        masterEvent.Nickname__c = 'ME - Nck';
        masterEvent.Name = 'Master Event REG ONLY';
        insert masterEvent; 
        
        // expect that the additional passes were NOT created.
        System.assertEquals(true, [SELECT Id
                                FROM Product2
                               	WHERE EE_Event__c = :masterEvent.id
                               	AND Sponsorship__c = 'Additional Pass'].isEmpty());
        
        
    	Test.stopTest();
    }
    
    static testMethod void testDateException() {
    	Test.startTest();
        // create event starting 65 days from now.
    	Events__c masterEvent = testData.createEvent(false);
        masterEvent.Nickname__c = 'ME - Nck';
        masterEvent.Name = 'Master Event';
        masterEvent.Event_Start_Date__c = System.now().addDays(65).date();
        masterEvent.Event_End_Date__c = System.now().addDays(66).date();
        insert masterEvent; 
        
        // expect that the additional passes were NOT created.
        System.assertEquals(true, [SELECT Id
                                FROM Product2
                               	WHERE EE_Event__c = :masterEvent.id
                               	AND Sponsorship__c = 'Additional Pass'].isEmpty());
        
        // create event starting 10 days in the past.
    	Events__c pastEvent = testData.createEvent(false);
        pastEvent.Nickname__c = 'ME - Nck';
        pastEvent.Name = 'Master Event';
        pastEvent.Event_Start_Date__c = System.now().addDays(-1).date();
        insert pastEvent; 
        
        // expect that the additional passes were NOT created.
        System.assertEquals(true, [SELECT Id
                                FROM Product2
                               	WHERE EE_Event__c = :pastEvent.id
                               	AND Sponsorship__c = 'Additional Pass'].isEmpty());
    	Test.stopTest();
    }
	*/
}