force-app/main/default/objects/Events__c/Events__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >Standard_Event_Compact_Layout</compactLayoutAssignment>
    <description
  >These are e.Republic Events - tradeshows, executive events, webinars, roundtables, custom events, etc.</description>
    <label>Event or Conference</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events and Conferences</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >Registration_Compact_Layout</compactLayoutAssignment>
    <description
  >This is a registration for any event, conference, forum, webinar, etc. across all e.Republic business units.</description>
    <label>Registration</label>
    <nameField>
        <displayFormat>REG-{000000}</displayFormat>
        <label>Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/fields/Attendee_Name__c.field-meta.xml
<CustomField>
    <fullName>Attendee_Name__c</fullName>
    <formula
  >Registrant_Name__r.LastName &amp;&quot;, &quot;&amp; Registrant_Name__r.FirstName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Attendee Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Events__c</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Event_No_Show__c.field-meta.xml
<CustomField>
    <fullName>Event_No_Show__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Registrant did not show up at this event.</description>
    <label>No Show / Cancellation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Non_Qual__c.field-meta.xml
<CustomField>
    <fullName>Non_Qual__c</fullName>
    <defaultValue>false</defaultValue>
    <description
  >This field indicates that a registration is not qualified to count as a lead for this event or webinar campaign. Examples include staff, students, test records, or people that are not meeting filter requirements.</description>
    <inlineHelpText
  >This field indicates that a registration is not qualified to count as a lead for this event or webinar campaign. Examples include staff, students, test records, or people that are not meeting filter requirements.</inlineHelpText>
    <label>Non-Qual</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Promo_Code__c.field-meta.xml
<CustomField>
    <fullName>Promo_Code__c</fullName>
    <label>Promo Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Reg_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Reg_Company_Name__c</fullName>
    <formula>Registrant_Name__r.Company_Name_Holder__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Reg_Type__c.field-meta.xml
<CustomField>
    <fullName>Reg_Type__c</fullName>
    <inlineHelpText
  >Enter the type of registration i.e. Sponsor, Speaker, etc.</inlineHelpText>
    <label>Reg Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Association</fullName>
            </value>
            <value>
                <fullName>Govt Attendee</fullName>
                <default>true</default>
                <label>Govt Attendee</label>
            </value>
            <value>
                <fullName>Industry Attendee</fullName>
            </value>
            <value>
                <fullName>Sponsor</fullName>
            </value>
            <value>
                <fullName>Press</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>1</fullName>
                <isActive>false</isActive>
                <label>1</label>
            </value>
            <value>
                <fullName>ABSPON</fullName>
                <isActive>false</isActive>
                <label>ABSPON</label>
            </value>
            <value>
                <fullName>ADBD</fullName>
                <isActive>false</isActive>
                <label>ADBD</label>
            </value>
            <value>
                <fullName>ADBD/SPKR</fullName>
                <isActive>false</isActive>
                <label>ADBD/SPKR</label>
            </value>
            <value>
                <fullName>Advisory Board</fullName>
                <isActive>false</isActive>
                <label>Advisory Board</label>
            </value>
            <value>
                <fullName>GOVCOMP</fullName>
                <isActive>false</isActive>
                <label>GOVCOMP</label>
            </value>
            <value>
                <fullName>GOVPAID</fullName>
                <isActive>false</isActive>
                <label>GOVPAID</label>
            </value>
            <value>
                <fullName>Gov Attendee</fullName>
                <isActive>false</isActive>
                <label>Gov Attendee</label>
            </value>
            <value>
                <fullName>Government Attendee</fullName>
                <isActive>false</isActive>
                <label>Government Attendee</label>
            </value>
            <value>
                <fullName>Government Complimentary</fullName>
                <isActive>false</isActive>
                <label>Government Complimentary</label>
            </value>
            <value>
                <fullName>Government Paid</fullName>
                <isActive>false</isActive>
                <label>Government Paid</label>
            </value>
            <value>
                <fullName>INDCOMP</fullName>
                <isActive>false</isActive>
                <label>INDCOMP</label>
            </value>
            <value>
                <fullName>INDPAID</fullName>
                <isActive>false</isActive>
                <label>INDPAID</label>
            </value>
            <value>
                <fullName>Industry</fullName>
                <isActive>false</isActive>
                <label>Industry</label>
            </value>
            <value>
                <fullName>Industry Atendee</fullName>
                <isActive>false</isActive>
                <label>Industry Atendee</label>
            </value>
            <value>
                <fullName>Industry Complimentary</fullName>
                <isActive>false</isActive>
                <label>Industry Complimentary</label>
            </value>
            <value>
                <fullName>Industry Paid</fullName>
                <isActive>false</isActive>
                <label>Industry Paid</label>
            </value>
            <value>
                <fullName>Item Created</fullName>
                <isActive>false</isActive>
                <label>Item Created</label>
            </value>
            <value>
                <fullName>O Online</fullName>
                <isActive>false</isActive>
                <label>O Online</label>
            </value>
            <value>
                <fullName>PRES</fullName>
                <isActive>false</isActive>
                <label>PRES</label>
            </value>
            <value>
                <fullName>Private</fullName>
                <isActive>false</isActive>
                <label>Private</label>
            </value>
            <value>
                <fullName>Private Sector</fullName>
                <isActive>false</isActive>
                <label>Private Sector</label>
            </value>
            <value>
                <fullName>Public</fullName>
                <isActive>false</isActive>
                <label>Public</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Registrant_Email__c.field-meta.xml
<CustomField>
    <fullName>Registrant_Email__c</fullName>
    <description
  >The email address of the person who registered. Used for Eloqua Lookup.</description>
    <formula>Registrant_Name__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText
  >The email address of the person who registered. Used for Eloqua Lookup.</inlineHelpText>
    <label>Registrant Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Registrant_Name__c.field-meta.xml
<CustomField>
    <fullName>Registrant_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registrant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Registrant_Title__c.field-meta.xml
<CustomField>
    <fullName>Registrant_Title__c</fullName>
    <formula>Registrant_Name__r.Title</formula>
    <label>Title</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ef3_disqualify_registrations_controller.cls
/*
Michael Tel 7/8/2015
used by the ef3_disqualify_registrations vf page
test cases in eventRegistration_test.cls
*/
public with sharing class ef3_disqualify_registrations_controller {
  //public  String[] pages = new String[]{};
  public String pagination { get; private set; }
  private List<Registration__c> registrations;
  private ID eventId;
  public Integer currentPage = 1;
  private Integer maxPage = 1;
  private Integer offset = 0;
  private Events__c event;

  private final Integer itemsPerPage = 100;
  public String sortOrder { get; set; } // = 'Name Desc'; // firstName, lastName, title, company, email, non_qual, no-show p

  //StandardSetController
  public ef3_disqualify_registrations_controller(
    ApexPages.StandardSetController controller
  ) {
    eventId = (ID) ApexPages.currentPage().getParameters().get('id');
    sortOrder = ApexPages.currentPage().getParameters().get('sortOrder');
    if (sortOrder == null)
      sortOrder = 'Name Desc';

    String cp = ApexPages.currentPage().getParameters().get('page');
    if (cp != null)
      currentPage = Integer.valueOf(cp);
    offset = (currentPage - 1) * itemsPerPage;
    event = [SELECT Id, Name FROM Events__c WHERE Id = :this.eventId];

    loadRegistrations();

    // pagination
    pagination = '';
    Integer numResults = Database.countQuery(
      'SELECT count() FROM Registration__c WHERE Event__c = :eventId'
    );
    if (numResults > itemsPerPage) {
      maxPage = numResults / itemsPerPage + 1;
      for (integer p = 1; p <= maxPage; p++) {
        if (p == currentPage)
          pagination = pagination + ' &nbsp; <b> page ' + currentPage + '</b>';
        else
          pagination =
            pagination +
            ' &nbsp; <a href="/apex/ef3_disqualify_registrations?id=' +
            eventId +
            '&sortorder=' +
            sortorder +
            '&page=' +
            p +
            '" target="top" >page ' +
            p +
            '</a>';
        //pages.add('/apex/ef3_disqualify_registrations?id='+ eventId  +'&sortorder='+sortorder+'&page='+ p );
      }
    }
  }

  private void loadRegistrations() {
    String socl =
      'SELECT Id, Name, Attendee_Name__c,Registrant_Name__r.RecordTypeId,  Registrant_Name__r.firstName, Registrant_Name__r.lastName,  Non_Qual__c, Event_No_Show__c, Reg_Company_Name__c,Reg_Type__c, Promo_Code__c, Registrant_Email__c ,Registrant_Title__c, CreatedBy.Name' +
      ' FROM Registration__c WHERE Event__c = :eventId  ORDER BY ' +
      sortOrder +
      '  LIMIT ' +
      itemsPerPage +
      ' OFFSET ' +
      offset;
    registrations = Database.query(socl);
  }

  public String getEventName() {
    return (String) event.Name;
  }

  public String getEventId() {
    return (ID) this.eventId;
  }

  public List<Registration__c> getRegistrations() {
    return this.registrations;
  }

  public PageReference save() {
    try {
      update (this.registrations);
    } catch (System.DMLException e) {
      ApexPages.addMessages(e);
      return null;
    }

    if (currentPage < maxpage)
      return new PageReference(
          '/apex/ef3_disqualify_registrations?id=' +
            eventId +
            '&sortorder=' +
            sortorder +
            '&page=' +
            (currentPage + 1)
        )
        .setRedirect(true);

    // After Save, navigate to the default view page:
    return (new ApexPages.StandardController(this.event)).view();
  }
}