force-app/main/default/objects/Events__c/Events__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >Standard_Event_Compact_Layout</compactLayoutAssignment>
    <description
  >These are e.Republic Events - tradeshows, executive events, webinars, roundtables, custom events, etc.</description>
    <label>Event or Conference</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events and Conferences</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Events__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description
  >This is the status of the event as determined by Logistics.</description>
    <inlineHelpText
  >This is the status of the event as determined by Logistics.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Venue Set</fullName>
            </value>
            <value>
                <fullName>Program Set</fullName>
            </value>
            <value>
                <fullName>In-Production</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Save_the_Date</fullName>
                <label>Save the Date</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/product_trigger_test.cls
@isTest
public class product_trigger_test {
  static testMethod void myUnitTest() {
    Test.startTest();
    Events__c e = new Events__c(
      Name = 'test event',
      status__c = 'Planned',
      RecordTypeId = '01230000000ueuw'
    );
    insert e;

    Product2 p = new Product2(
      Name = 'test attendee product',
      EE_Event__c = e.Id,
      Sponsorship__c = 'Attendee'
    );
    insert p;
    Test.stopTest();
  }
}