force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <description>&quot;Masterclasses&quot; e.Republic Edition</description>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <description>The brand of the class (GT, GOV, CDE, EM)</description>
    <label>Brand</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Class_Reg__c/Class_Reg__c.object-meta.xml
<CustomObject>
    <description>A lead that has registered for a class</description>
    <label>Class Registration</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Reg No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Class_Reg__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>The class the student is registered for</description>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Class_Reg__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Full detail of the contact who is the student</description>
    <label>Student</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Class Registrations</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Class_Reg__c/fields/Non_Qual__c.field-meta.xml
<CustomField>
    <fullName>Non_Qual__c</fullName>
    <defaultValue>false</defaultValue>
    <description
  >Indicates that this student is not qualified to be delivered as a lead.</description>
    <label>Non-Qual</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Class_Reg_Trigger_test.cls
@isTest
public with sharing class Class_Reg_Trigger_test {
  static testMethod void myUnitTest() {
    Test.startTest();
    Contact registrant = testData.createContact();
    Class_Reg__c class1 = new Class_Reg__c(
      Non_Qual__c = true,
      Contact__c = registrant.Id,
      Class__c = testData.createClassWithBrand('GOVERNING').Id
    );
    insert class1;
    // Class__c cl1r = [SELECT Brand__c FROM Class__c WHERE Id = :class1.Class__c];
    // System.assertEquals(cl1r.Brand__c, 'GOVERNING');
    // Contact ct1 =  [SELECT Last_GOV_Class__c FROM Contact WHERE Id = :registrant.Id];
    // System.assertEquals(ct1.Last_GOV_Class__c, class1.Id);

    // Class_Reg__c class2 = new Class_Reg__c(
    //     Non_Qual__c = TRUE,
    //     Contact__c = registrant.Id,
    //     Class__c = testData.createClassWithBrand('GOVTECH').Id
    // );
    // insert class2;
    // Contact ct2 =  [SELECT Last_GT_Class__c FROM Contact WHERE Id = :registrant.Id];
    // System.assertEquals(ct2.Last_GT_Class__c, class2.Id);

    // Class_Reg__c class3 = new Class_Reg__c(
    //     Non_Qual__c = TRUE,
    //     Contact__c = registrant.Id,
    //     Class__c = testData.createClassWithBrand('CDE').Id
    // );
    // insert class3;
    // Contact ct3 =  [SELECT Last_CDE_Class__c FROM Contact WHERE Id = :registrant.Id];
    // System.assertEquals(ct3.Last_CDE_Class__c, class3.Id);

    // Class_Reg__c class4 = new Class_Reg__c(
    //     Non_Qual__c = TRUE,
    //     Contact__c = registrant.Id,
    //     Class__c = testData.createClassWithBrand('EMERGENCYMGMT').Id
    // );
    // insert class4;
    // Contact ct4 =  [SELECT Last_EM_Class__c FROM Contact WHERE Id = :registrant.Id];
    // System.assertEquals(ct4.Last_EM_Class__c, class4.Id);

    // class1.Non_Qual__c = FALSE;
    // update class1;
    // class2.Non_Qual__c = TRUE;
    // update class1;

    // delete class1;

    Test.stopTest();
  }
}