force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <description>&quot;Masterclasses&quot; e.Republic Edition</description>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class_Reg__c/Class_Reg__c.object-meta.xml
<CustomObject>
    <description>A lead that has registered for a class</description>
    <label>Class Registration</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Reg No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Class_Reg__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>The class the student is registered for</description>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Class_Reg__c/fields/Class_Complete__c.field-meta.xml
<CustomField>
    <fullName>Class_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>All sessions in the class have been completed.</description>
    <label>Class Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Class_Session__c/Class_Session__c.object-meta.xml
<CustomObject>
    <description>A video session belonging to a class.</description>
    <label>Class Session</label>
    <nameField>
        <displayFormat>Session-{0000}</displayFormat>
        <label>Class Session No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class_Session__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The class which this session belongs to</description>
    <inlineHelpText>The class which this session belongs to</inlineHelpText>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Class Sessions</relationshipLabel>
    <relationshipName>Class_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Status__c/Session_Status__c.object-meta.xml
<CustomObject>
    <description>A student&apos;s status in a session</description>
    <label>Session Status</label>
    <nameField>
        <displayFormat>SS-{0000}</displayFormat>
        <label>Status No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Status</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Status__c/fields/Class_Reg__c.field-meta.xml
<CustomField>
    <fullName>Class_Reg__c</fullName>
    <description>The student who is engaging in the session.</description>
    <inlineHelpText>The student who is engaging in the session.</inlineHelpText>
    <label>Class Reg</label>
    <referenceTo>Class_Reg__c</referenceTo>
    <relationshipLabel>Session Status</relationshipLabel>
    <relationshipName>Class_Status</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session_Status__c/fields/Class_Session__c.field-meta.xml
<CustomField>
    <fullName>Class_Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The session which this status is reporting on.</description>
    <inlineHelpText
  >The session which this status is reporting on.</inlineHelpText>
    <label>Class Session</label>
    <referenceTo>Class_Session__c</referenceTo>
    <relationshipName>Class_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Status__c/fields/Complete_Pct__c.field-meta.xml
<CustomField>
    <fullName>Complete_Pct__c</fullName>
    <defaultValue>0.0</defaultValue>
    <description
  >The percentage of the student&apos;s completion of the session. (Usually the percentage of playback in the video.)</description>
    <inlineHelpText
  >The percentage of the student&apos;s completion of the session. (Usually the percentage of playback in the video.)</inlineHelpText>
    <label>Complete Pct</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/Class_Status_Trigger_test.cls
@isTest
public with sharing class Class_Status_Trigger_test {
  public static testMethod void testStatusAndCompletion() {
    Class__c cl = testData.createClass();
    Class_Reg__c st = testData.createStudent(cl.Id);
    System.assertEquals(false, st.Class_Complete__c);
    List<Class_Session__c> sessions = [
      SELECT Id
      FROM Class_Session__c
      WHERE Class__c = :cl.Id
    ];
    for (Class_Session__c cs : sessions) {
      Session_Status__c cst = new Session_Status__c(
        Class_Reg__c = st.Id,
        Class_Session__c = cs.Id,
        Complete_Pct__c = 50.0
      );
      insert cst;
    }
    Class_Reg__c st_status = [
      SELECT Class_Complete__c
      FROM Class_Reg__c
      WHERE Id = :st.Id
    ];
    System.assertEquals(false, st_status.Class_Complete__c);
    List<Session_Status__c> statuses = [
      SELECT Id, Complete_Pct__c
      FROM Session_Status__c
      WHERE Class_Reg__c = :st.Id AND Class_Session__r.Class__c = :cl.Id
    ];
    System.assertEquals(2, statuses.size());
    for (Session_Status__c status : statuses) {
      status.Complete_Pct__c = 100.0;
      update status;
    }
    Class_Reg__c st_status2 = [
      SELECT Class_Complete__c
      FROM Class_Reg__c
      WHERE Id = :st.Id
    ];
    System.assertEquals(true, st_status2.Class_Complete__c);
  }
}