force-app/main/default/objects/Agreement__c/Agreement__c.object-meta.xml
<CustomObject>
    <label>Agreement</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Agreement</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Agreement__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Agreement__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Agreements</relationshipLabel>
    <relationshipName>Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Agreement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Out for Signature</fullName>
            </value>
            <value>
                <fullName>Printed</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Discarded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityMergeController_test.cls
@isTest(SeeAllData=true)
public class OpportunityMergeController_test {
  static testMethod void testGetOpportunity() {
    Opportunity opp = testData.createOpportunity();
    Opportunity testOpp = OpportunityMergeController.getOpportunity(opp.Id);
    System.assertEquals(testOpp.Id, opp.Id);
    System.assertEquals(testOpp.Name, opp.Name);
  }
  static testMethod void testSearchOpportunities() {
    testData.createOpportunity();
    testData.createOpportunity();
    testData.createOpportunity();
    List<Opportunity> searchResults = OpportunityMergeController.searchOpportunities(
      'michael test opportunity'
    );
    System.assertEquals(searchResults.size(), 3);
  }
  static testMethod void testMergeOpportunities() {
    Opportunity winnerOpp = testData.createOpportunity();
    Opportunity loserOpp = testData.createOpportunity();

    // Add agreements, contracts, files and contact roles
    Agreement__c ag = new Agreement__c(
      Opportunity__c = loserOpp.Id,
      Description__c = 'Losing Agreement',
      Status__c = 'Draft'
    );

    insert ag;

    Account ac = testData.createAccount();

    Contract ct = new Contract(
      Name = 'Test Losing Contract',
      Status = 'Draft',
      Primary_Opportunity__c = loserOpp.Id,
      AccountId = ac.Id
    );

    insert ct;

    testData.attachFile(loserOpp.Id);

    List<Id> losers = new List<Id>{ loserOpp.Id };
    String loserIds = String.join(losers, ',');
    OpportunityMergeController.mergeOpportunities(winnerOpp.Id, loserIds);

    // check files
    System.assertEquals(
      1,
      database.countQuery(
        'SELECT COUNT() FROM ContentDocumentLink WHERE LinkedEntityId =\'' +
          winnerOpp.Id +
          '\''
      )
    );
    // check contract
    System.assertEquals(
      false,
      [SELECT Id FROM Contract WHERE Primary_Opportunity__c = :winnerOpp.Id]
        .isEmpty()
    );
    // check that agreements were moved over
    System.assertEquals(
      false,
      [SELECT Id FROM Agreement__c WHERE Opportunity__c = :winnerOpp.Id]
        .isEmpty()
    );
    // check that the OpportunityLineItems have been added.
    System.assertEquals(
      10,
      database.countQuery(
        'SELECT COUNT() FROM OpportunityLineItem WHERE OpportunityId =\'' +
          winnerOpp.Id +
          '\''
      )
    );
    // check that the Opportunity has been deleted.
    System.assertEquals(
      true,
      [SELECT Id FROM Opportunity WHERE Id = :loserOpp.Id].isEmpty()
    );
  }
}