force-app/main/default/objects/Publication__c/Publication__c.object-meta.xml
<CustomObject>
    <label>Publication</label>
    <nameField>
        <label>Publication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >Subscription_Compact_Layout</compactLayoutAssignment>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB#{0000000}</displayFormat>
        <label>Sub Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Batch__c.field-meta.xml
<CustomField>
    <fullName>Batch__c</fullName>
    <description
  >Indicates the number of the batch that the source documents are kept in for auditing.</description>
    <inlineHelpText
  >Indicates the number of the batch that the source documents are kept in for auditing.</inlineHelpText>
    <label>Batch</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <description>Reason for the cancellation of the subscription.</description>
    <inlineHelpText
  >Reason for the cancellation of the subscription.</inlineHelpText>
    <label>Cancellation Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BAD ADDRESS</fullName>
                <label>Bad Address</label>
            </value>
            <value>
                <fullName>BAD EMAIL</fullName>
                <label>Bad Email</label>
            </value>
            <value>
                <fullName>CR</fullName>
                <label>Customer Request</label>
            </value>
            <value>
                <fullName>DECEASED</fullName>
                <label>Deceased</label>
            </value>
            <value>
                <fullName>DUP</fullName>
                <label>Duplicate</label>
            </value>
            <value>
                <fullName>No longer works at organization</fullName>
            </value>
            <value>
                <fullName>PUB</fullName>
                <label>Publisher</label>
            </value>
            <value>
                <fullName>RETIRED</fullName>
                <label>Retired</label>
            </value>
            <value>
                <fullName>Bad Email (Global Opt Out)</fullName>
            </value>
            <value>
                <fullName>Bad Email (Missing Email)</fullName>
            </value>
            <value>
                <fullName>Bad Email (Hard Bounce)</fullName>
            </value>
            <value>
                <fullName>Bad Email (Inactive Email)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/PIQ__c.field-meta.xml
<CustomField>
    <fullName>PIQ__c</fullName>
    <description
  >Personal Identifying Question used for audited publications.</description>
    <inlineHelpText
  >Personal Identifying Question used for audited publications.</inlineHelpText>
    <label>PIQ</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Promo_Code__c.field-meta.xml
<CustomField>
    <fullName>Promo_Code__c</fullName>
    <description
  >Promotional code used to track incoming subscription requests.</description>
    <inlineHelpText
  >Promotional code used to track incoming subscription requests.</inlineHelpText>
    <label>Promo Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Publication__c.field-meta.xml
<CustomField>
    <fullName>Publication__c</fullName>
    <description
  >Indicates the publication that this is a subscription for.</description>
    <inlineHelpText
  >Indicates the publication that this is a subscription for.</inlineHelpText>
    <label>Publication</label>
    <referenceTo>Publication__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Qual__c.field-meta.xml
<CustomField>
    <fullName>Qual__c</fullName>
    <description>Qualification status of the subscription.</description>
    <inlineHelpText>Qualification status of the subscription.</inlineHelpText>
    <label>Qual</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Requestor</fullName>
            </value>
            <value>
                <fullName>Non-Requestor</fullName>
            </value>
            <value>
                <fullName>Paid Requestor</fullName>
            </value>
            <value>
                <fullName>Lifetime Requestor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Qual_Date__c.field-meta.xml
<CustomField>
    <fullName>Qual_Date__c</fullName>
    <description>Date of the incoming subscription request.</description>
    <inlineHelpText>Date of the incoming subscription request.</inlineHelpText>
    <label>Qual Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Indicates the source of the subscription.</description>
    <inlineHelpText>Indicates the source of the subscription.</inlineHelpText>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1A</fullName>
            </value>
            <value>
                <fullName>1B</fullName>
            </value>
            <value>
                <fullName>1C</fullName>
            </value>
            <value>
                <fullName>2A</fullName>
            </value>
            <value>
                <fullName>2B</fullName>
            </value>
            <value>
                <fullName>2C</fullName>
            </value>
            <value>
                <fullName>3A</fullName>
            </value>
            <value>
                <fullName>3B</fullName>
            </value>
            <value>
                <fullName>4A</fullName>
            </value>
            <value>
                <fullName>4B</fullName>
            </value>
            <value>
                <fullName>4C</fullName>
            </value>
            <value>
                <fullName>5A</fullName>
            </value>
            <value>
                <fullName>5B</fullName>
            </value>
            <value>
                <fullName>5C</fullName>
            </value>
            <value>
                <fullName>5D</fullName>
            </value>
            <value>
                <fullName>5E</fullName>
            </value>
            <value>
                <fullName>5F</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of the subscription.</description>
    <inlineHelpText>The status of the subscription.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Subscriber__c.field-meta.xml
<CustomField>
    <fullName>Subscriber__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description
  >This is the contact record that this subscription is associated with.</description>
    <inlineHelpText
  >This is the contact record that this subscription is associated with.</inlineHelpText>
    <label>Subscriber</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <description
  >Indicates the delivery version for this subscription.</description>
    <inlineHelpText
  >Indicates the delivery version for this subscription.</inlineHelpText>
    <label>Version</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Print</fullName>
            </value>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
            <value>
                <fullName>D</fullName>
                <isActive>false</isActive>
                <label>D</label>
            </value>
            <value>
                <fullName>No Comp</fullName>
                <isActive>false</isActive>
                <label>No Comp</label>
            </value>
            <value>
                <fullName>Non-Requestor</fullName>
                <isActive>false</isActive>
                <label>Non-Requestor</label>
            </value>
            <value>
                <fullName>P</fullName>
                <isActive>false</isActive>
                <label>P</label>
            </value>
            <value>
                <fullName>P - Print</fullName>
                <isActive>false</isActive>
                <label>P - Print</label>
            </value>
            <value>
                <fullName>Prev</fullName>
                <isActive>false</isActive>
                <label>Prev</label>
            </value>
            <value>
                <fullName>Printrint</fullName>
                <isActive>false</isActive>
                <label>Printrint</label>
            </value>
            <value>
                <fullName>Removed</fullName>
                <isActive>false</isActive>
                <label>Removed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/subscription_expiration_before_save_test.cls
@isTest
private class subscription_expiration_before_save_test {
  // this method tests both subscribtion triggers

  // CDE: 'a0Qa000000J4s63EAB'  GOV: a0Qa000000J4q7BEAR      GT: a0Qa000000J4s5tEAB    no more  EM: a0Qa000000J4s5yEAB

  static testMethod void test_this() {
    Contact c1 = testData.createContact();
    // create subscription
    List<Subscription__c> subs = new List<Subscription__c>();
    List<Id> publications = new List<ID>{
      'a0Qa000000J4q7BEAR',
      'a0Qa000000J4s5tEAB'
    }; //'a0Qa000000J4s63EAB',
    for (Id pub_id : publications) {
      Subscription__c sub1 = new Subscription__c(
        Batch__c = '',
        Cancellation_Reason__c = '',
        PIQ__c = '',
        Promo_Code__c = '1401WEB',
        Publication__c = pub_id, // GT
        Qual__c = 'Requestor',
        Qual_Date__c = Date.today(),
        Source__c = '1C',
        Status__c = 'Active',
        Subscriber__c = c1.Id,
        Version__c = 'Print'
      );
      subs.add(sub1);
    }
    Subscription__c subExp = new Subscription__c(
      Batch__c = '',
      Cancellation_Reason__c = '',
      PIQ__c = '',
      Promo_Code__c = '1401WEB',
      Publication__c = 'a0Qa000000J4s5tEAB', // GT
      Qual__c = 'Requestor',
      Qual_Date__c = Date.today(),
      Source__c = '1C',
      Status__c = 'Expired',
      Subscriber__c = c1.Id,
      Version__c = 'Print'
    );
    subs.add(subExp);
    List<Subscription__c> subs2 = new List<Subscription__c>();
    for (Id pub_id : publications) {
      Subscription__c sub2 = new Subscription__c(
        Batch__c = '',
        Cancellation_Reason__c = '',
        PIQ__c = '',
        Promo_Code__c = '1401WEB',
        Publication__c = pub_id, // GT
        Qual__c = 'Requestor',
        Qual_Date__c = Date.today(),
        Source__c = '1C',
        Status__c = 'Active',
        Subscriber__c = c1.Id,
        Version__c = 'Print'
      );
      subs2.add(sub2);
    }
    Test.startTest();
    insert subs;
    insert subs2;
    Test.stopTest();
  }
}