force-app/main/default/objects/Paper__c/Paper__c.object-meta.xml
<CustomObject>
    <description>CRM Management of white papers and other assets.</description>
    <label>Paper</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Papers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Paper__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The client sponsoring this asset.</description>
    <inlineHelpText>The client sponsoring this asset.</inlineHelpText>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Papers</relationshipLabel>
    <relationshipName>Papers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Papers_Update_Trigger_test.cls
@isTest
public with sharing class Papers_Update_Trigger_test {
  static testMethod void paperTriggerTest() {
    Paper__c p = testData.createPaper('GOVERNING');
    Account a = testData.createAccount();
    DmlException expectedException;
    try {
      p.Client__c = a.Id;
      update p;
    } catch (DmlException dmx) {
      expectedException = dmx;
    }
    System.assertEquals(
      'FIELD_CUSTOM_VALIDATION_EXCEPTION',
      expectedException.getDmlStatusCode(0)
    );
  }
}