force-app/main/default/objects/Paper__c/Paper__c.object-meta.xml
<CustomObject>
    <description>CRM Management of white papers and other assets.</description>
    <label>Paper</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Papers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Paper__c/recordTypes/Paper.recordType-meta.xml
<RecordType>
    <fullName>Paper</fullName>
    <active>true</active>
    <description
  >Standard Paper - Sponsored Papers, Reports (for Govt Audience)</description>
    <label>Paper</label>
</RecordType>

force-app/main/default/objects/Paper_Download__c/Paper_Download__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >Paper_Download_Compact_Layout</compactLayoutAssignment>
    <label>Paper Download</label>
    <nameField>
        <displayFormat>DL-{000000}</displayFormat>
        <label>Paper Download Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Paper Downloads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Paper_Download__c/fields/Non_Qual__c.field-meta.xml
<CustomField>
    <fullName>Non_Qual__c</fullName>
    <defaultValue>false</defaultValue>
    <description
  >Indicates that this download is not qualified to be delivered as a lead.</description>
    <inlineHelpText
  >Indicates that this download is not qualified to be delivered as a lead.</inlineHelpText>
    <label>Non-Qual</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Paper_Download__c/fields/Paper__c.field-meta.xml
<CustomField>
    <fullName>Paper__c</fullName>
    <description>Indicates which paper or asset was downloaded.</description>
    <inlineHelpText
  >Indicates which paper or asset was downloaded.</inlineHelpText>
    <label>Paper</label>
    <referenceTo>Paper__c</referenceTo>
    <relationshipLabel>Paper Downloads</relationshipLabel>
    <relationshipName>Paper_Downloads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Paper_Download__c/fields/Registrant__c.field-meta.xml
<CustomField>
    <fullName>Registrant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description
  >Contact record for the person that downloaded the paper.</description>
    <inlineHelpText
  >Contact record for the person that downloaded the paper.</inlineHelpText>
    <label>Registrant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Paper Downloads</relationshipLabel>
    <relationshipName>Paper_Downloads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/paper_download_test.cls
@isTest
private class paper_download_test {
  static testMethod void myUnitTest() {
    Test.startTest();
    Contact registrant = testData.createContact();
    Paper_Download__c paper = new Paper_Download__c(
      Non_Qual__c = true,
      Registrant__c = registrant.Id,
      Paper__c = testData.createPaper('GOVERNING').Id
    );
    insert paper;

    Paper_Download__c paper2 = new Paper_Download__c(
      Non_Qual__c = true,
      Registrant__c = registrant.Id,
      Paper__c = testData.createPaper('GT').Id
    );
    insert paper2;

    Paper_Download__c paper3 = new Paper_Download__c(
      Non_Qual__c = true,
      Registrant__c = registrant.Id,
      Paper__c = testData.createPaper('CDE').Id
    );
    insert paper3;

    paper.Non_Qual__c = false;
    update paper;
    paper.Non_Qual__c = true;
    update paper;

    delete paper;

    Test.stopTest();
  }
}