force-app/main/default/objects/Contact_Us__c/Contact_Us__c.object-meta.xml
<CustomObject>
    <label>Contact Us</label>
    <nameField>
        <displayFormat>CU-{0000}</displayFormat>
        <label>Contact Us Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Us</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Us__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact_Us__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact_Us__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact_Us__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact_Us__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <label>Organization</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact_Us__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact_Us__c/fields/Topic__c.field-meta.xml
<CustomField>
    <fullName>Topic__c</fullName>
    <label>Topic</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Article Submissions</fullName>
            </value>
            <value>
                <fullName>Editorial</fullName>
            </value>
            <value>
                <fullName>Events</fullName>
            </value>
            <value>
                <fullName>Sales &amp; Advertising</fullName>
            </value>
            <value>
                <fullName>Subscriptions</fullName>
            </value>
            <value>
                <fullName>Editorial and Article Submissions</fullName>
                <isActive>false</isActive>
                <label>Editorial and Article Submissions</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>Press Releases</fullName>
                <isActive>false</isActive>
                <label>Press Releases</label>
            </value>
            <value>
                <fullName>Website Bugs</fullName>
                <isActive>false</isActive>
                <label>Website Bugs</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContactUsRequestController_test.cls
@isTest
public class ContactUsRequestController_test {
  public static testMethod void testContactUsReqController() {
    ContactUsRequestController testCtrl = new ContactUsRequestController();
    List<selectOption> requestTopics = testCtrl.getRequestTopic();
    System.assert(requestTopics.size() > 1);

    List<selectOption> requestTopic = testCtrl.getRequestTopic();
    System.assert(requestTopic.size() > 1);

    Contact_Us__c pr = testCtrl.getTheContactRequest();

    // Instantiate a new controller with all parameters in the page
    ContactUsRequestController ctrl = makeContactRequest(
      new ContactUsRequestController()
    );
    PageReference res = ctrl.submit();

    // Verify that the success page displays
    System.assertEquals('/apex/ContactUsRequest?s=1', res.getUrl());

    Contact_Us__c pr_res = [
      SELECT
        First_Name__c,
        Last_Name__c,
        Phone__c,
        Email__c,
        Organization__c,
        Topic__c,
        Message__c
      FROM Contact_Us__c
      ORDER BY CreatedDate DESC
      LIMIT 1
    ];

    System.assertEquals('Joe', pr_res.First_Name__c);
    System.assertEquals('McTesterson', pr_res.Last_Name__c);
    System.assertEquals('(999) 999-9999', pr_res.Phone__c);
    System.assertEquals('j.mctest@gmail.net', pr_res.Email__c);
    System.assertEquals('Testsers Inc.', pr_res.Organization__c);
    System.assertEquals('Events', pr_res.Topic__c);
    System.assertEquals('Hey, I\'d like to buy stuff!', pr_res.Message__c);
  }

  private static ContactUsRequestController makeContactRequest(
    ContactUsRequestController ctrl
  ) {
    ctrl.First_Name = 'Joe';
    ctrl.Last_Name = 'McTesterson';
    ctrl.Phone = '(999) 999-9999';
    ctrl.Email = 'j.mctest@gmail.net';
    ctrl.Organization = 'Testsers Inc.';
    ctrl.RTopic = 'Events';
    ctrl.Message = 'Hey, I\'d like to buy stuff!';
    return ctrl;
  }
}