force-app/main/default/objects/SFL5_Projects__c/SFL5_Projects__c.object-meta.xml
<CustomObject>
    <compactLayoutAssignment
  >Project_Research_Compact_Layout</compactLayoutAssignment>
    <description
  >Projects are related to Accounts and optionally an opportunity.  The percent complete is based on the project checklist using a custom formula field.  Using workflow, it is suggested to create standard tasks based on the project stage field.  Calendar events can be scheduled to book consultants time.  Since outlook and salesforce.com integrate bidirectionally, it helps schedule internal and external resources.  

Time and expenses can also be tracked to projects.  
Documents like SOW&apos;s, progress reports, etc can be attached to projects.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SFL5_Projects__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SFL5_Projects__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SFL5_Projects__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account Based Marketing</fullName>
            </value>
            <value>
                <fullName>Banners</fullName>
            </value>
            <value>
                <fullName>Case Study</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
            <value>
                <fullName>Custom Event</fullName>
            </value>
            <value>
                <fullName>Custom Roundtable</fullName>
            </value>
            <value>
                <fullName>Editorial Roundtable</fullName>
            </value>
            <value>
                <fullName>Executive Q&amp;A</fullName>
            </value>
            <value>
                <fullName>Filtered Leads</fullName>
            </value>
            <value>
                <fullName>Go-to-Guide</fullName>
            </value>
            <value>
                <fullName>Handbook</fullName>
            </value>
            <value>
                <fullName>Infographic</fullName>
            </value>
            <value>
                <fullName>Issue Brief</fullName>
            </value>
            <value>
                <fullName>Lunch &amp; Learn Webinar</fullName>
            </value>
            <value>
                <fullName>Multi-Touch Nurture</fullName>
            </value>
            <value>
                <fullName>Newsletters</fullName>
            </value>
            <value>
                <fullName>Persona-Based Paper</fullName>
            </value>
            <value>
                <fullName>Position Paper</fullName>
            </value>
            <value>
                <fullName>Rapid Roadmap</fullName>
            </value>
            <value>
                <fullName>Research Report</fullName>
            </value>
            <value>
                <fullName>Shared Leads</fullName>
            </value>
            <value>
                <fullName>Social Toolkit</fullName>
            </value>
            <value>
                <fullName>Sponsored Article</fullName>
            </value>
            <value>
                <fullName>Standard Leads</fullName>
            </value>
            <value>
                <fullName>State-Specific Webinar</fullName>
            </value>
            <value>
                <fullName>Thought Leadership Paper</fullName>
            </value>
            <value>
                <fullName>Two-Step Nurture</fullName>
            </value>
            <value>
                <fullName>Virtual Conversation</fullName>
            </value>
            <value>
                <fullName>Webinar</fullName>
            </value>
            <value>
                <fullName>White Paper</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SFL5_Projects__c/fields/Project_Owner__c.field-meta.xml
<CustomField>
    <fullName>Project_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description
  >The person who is responsible for the management and completion of this project.</description>
    <inlineHelpText
  >The person who is responsible for the management and completion of this project.</inlineHelpText>
    <label>Project Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SFL5_Projects__c/fields/Project_Phase__c.field-meta.xml
<CustomField>
    <fullName>Project_Phase__c</fullName>
    <label>Project Phase</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Project_Status__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Waiting</fullName>
            </value>
            <value>
                <fullName>Scheduling Kick-off Call</fullName>
            </value>
            <value>
                <fullName>Waiting on Client</fullName>
            </value>
            <value>
                <fullName>Waiting on Content Studio</fullName>
            </value>
            <value>
                <fullName>Drafting Promo</fullName>
            </value>
            <value>
                <fullName>Event In Progress</fullName>
            </value>
            <value>
                <fullName>Engaging Writer</fullName>
            </value>
            <value>
                <fullName>Conducting SME Interviews</fullName>
            </value>
            <value>
                <fullName>Developing Outline</fullName>
            </value>
            <value>
                <fullName>Outline with Editor</fullName>
            </value>
            <value>
                <fullName>Outline with Client</fullName>
            </value>
            <value>
                <fullName>Conducting Public Sector Interviews</fullName>
            </value>
            <value>
                <fullName>Developing Draft</fullName>
            </value>
            <value>
                <fullName>Draft with Editor</fullName>
            </value>
            <value>
                <fullName>Draft with Client</fullName>
            </value>
            <value>
                <fullName>Developing Design</fullName>
            </value>
            <value>
                <fullName>Design with Editor</fullName>
            </value>
            <value>
                <fullName>Design with Client</fullName>
            </value>
            <value>
                <fullName>Pre-Launch</fullName>
            </value>
            <value>
                <fullName>In-Production</fullName>
            </value>
            <value>
                <fullName>Final Internal Review</fullName>
            </value>
            <value>
                <fullName>Delivering Leads</fullName>
            </value>
            <value>
                <fullName>Post-Production Required</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SFL5_Projects__c/fields/Project_Status__c.field-meta.xml
<CustomField>
    <fullName>Project_Status__c</fullName>
    <label>Select Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Waiting</fullName>
            </value>
            <value>
                <fullName>Case Study: Pre-Production</fullName>
            </value>
            <value>
                <fullName>Case Study: In-Production</fullName>
            </value>
            <value>
                <fullName>Case Study: Product Delivered</fullName>
            </value>
            <value>
                <fullName>Custom: Pre-Production</fullName>
            </value>
            <value>
                <fullName>Custom: In-Production</fullName>
            </value>
            <value>
                <fullName>Custom: Product Delivered</fullName>
            </value>
            <value>
                <fullName>Custom Event: Pre-Production</fullName>
            </value>
            <value>
                <fullName>Custom Event: In-Production</fullName>
            </value>
            <value>
                <fullName>Custom Event: Post-Event Delivery</fullName>
            </value>
            <value>
                <fullName>Custom Event: Product Delivered</fullName>
            </value>
            <value>
                <fullName>Custom Roundtable: Pre-Production</fullName>
            </value>
            <value>
                <fullName>Custom Roundtable: In-Production</fullName>
            </value>
            <value>
                <fullName>Custom Roundtable: Post-Event Delivery</fullName>
            </value>
            <value>
                <fullName>Custom Roundtable: Product Delivered</fullName>
            </value>
            <value>
                <fullName>Demand Gen: Pre-Production</fullName>
            </value>
            <value>
                <fullName>Demand Gen: In-Production</fullName>
            </value>
            <value>
                <fullName>Demand Gen: Product Delivered</fullName>
            </value>
            <value>
                <fullName>Editorial Roundtable: Pre-Production</fullName>
            </value>
            <value>
                <fullName>Editorial Roundtable: In-Production</fullName>
            </value>
            <value>
                <fullName>Editorial Roundtable: Post-Event Delivery</fullName>
            </value>
            <value>
                <fullName>Editorial Roundtable: Product Delivered</fullName>
            </value>
            <value>
                <fullName>Executive Q&amp;A: Pre-Production</fullName>
            </value>
            <value>
                <fullName>Executive Q&amp;A: In-Production</fullName>
            </value>
            <value>
                <fullName>Executive Q&amp;A: Product Delivered</fullName>
            </value>
            <value>
                <fullName>Go-to-Guide: Pre-Production</fullName>
            </value>
            <value>
                <fullName>Go-to-Guide: In-Production</fullName>
            </value>
            <value>
                <fullName>Go-to-Guide: Product Delivered</fullName>
            </value>
            <value>
                <fullName>Handbook: Pre-Production</fullName>
            </value>
            <value>
                <fullName>Handbook: In-Production</fullName>
            </value>
            <value>
                <fullName
        >Lunch &amp; Learn Webinar: Post-Event Delivery</fullName>
                <label>Lunch &amp; Learn Webinar: Post-Event Delivery</label>
            </value>
            <value>
                <fullName
        >Lunch &amp; Lunch Webinar: Product Delivered</fullName>
                <label>Lunch &amp; Lunch Webinar: Product Delivered</label>
            </value>
            <value>
                <fullName>Persona-Based Paper: Pre-Production</fullName>
            </value>
            <value>
                <fullName>Persona-Based Paper: In-Production</fullName>
            </value>
            <value>
                <fullName>Persona-Based Paper: Product Delivered</fullName>
            </value>
            <value>
                <fullName>Position Paper: Pre-Production</fullName>
            </value>
            <value>
                <fullName>Position Paper: In-Production</fullName>
            </value>
            <value>
                <fullName>Position Paper: Product Delivered</fullName>
            </value>
            <value>
                <fullName>Rapid Roadmap: Pre-Production</fullName>
            </value>
            <value>
                <fullName>Rapid Roadmap: In-Production</fullName>
            </value>
            <value>
                <fullName>Rapid Roadmap: Product Delivered</fullName>
            </value>
            <value>
                <fullName>Research Report: Pre-Production</fullName>
            </value>
            <value>
                <fullName>Research Report: In-Production</fullName>
            </value>
            <value>
                <fullName>Research Report: Product Delivered</fullName>
            </value>
            <value>
                <fullName>Roundtable: Pre-Production</fullName>
            </value>
            <value>
                <fullName>Roundtable: In-Production</fullName>
            </value>
            <value>
                <fullName>Roundtable: Product Delivered</fullName>
            </value>
            <value>
                <fullName>Social Toolkit: Pre-Production</fullName>
            </value>
            <value>
                <fullName>Social Toolkit: In-Production</fullName>
            </value>
            <value>
                <fullName>Social Toolkit: Product Delivered</fullName>
            </value>
            <value>
                <fullName>Sponsored Article: Pre-Production</fullName>
            </value>
            <value>
                <fullName>Sponsored Article: In-Production</fullName>
            </value>
            <value>
                <fullName>Sponsored Article: Product Delivered</fullName>
            </value>
            <value>
                <fullName>State-Specific Webinar: Pre-Production</fullName>
            </value>
            <value>
                <fullName>State-Specific Webinar: In-Production</fullName>
            </value>
            <value>
                <fullName>State-Specific Webinar: Post-Event Delivery</fullName>
            </value>
            <value>
                <fullName>State-Specific Webinar: Product Delivered</fullName>
            </value>
            <value>
                <fullName>Thought Leadership Paper: Pre-Production</fullName>
            </value>
            <value>
                <fullName>Thought Leadership Paper: In-Production</fullName>
            </value>
            <value>
                <fullName>Thought Leadership Paper: Product Delivered</fullName>
            </value>
            <value>
                <fullName>Virtual Conversation: Pre-Production</fullName>
            </value>
            <value>
                <fullName>Virtual Conversation: In-Production</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SFL5_Projects__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description
  >The account owner or person responsible for the delivery of this project. Formerly &quot;The sales rep responsible for the sale of the products being delivered in this project.&quot; but this resulted in departed staff appearing on projects.</description>
    <inlineHelpText
  >The account owner or person responsible for the delivery of this project from an account ownership perspective.</inlineHelpText>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/projectFromOppLineItem.cls
global class projectFromOppLineItem {
  @AuraEnabled
  webService static String createProject(Id line_item_id) {
    // Special_Terms_del__c,
    OpportunityLineItem l = [
      SELECT
        Id,
        Contract__c,
        Special_Terms_del__c,
        OpportunityId,
        Opportunity.Account.Concierge_1__c,
        Opportunity.Account.Id,
        Product2Id,
        Product2.Product_Category__c,
        Opportunity.Owner.Id,
        TotalPrice,
        AccountName__c,
        Project_Name_Text__c,
        Project_Name__c
      FROM OpportunityLineItem
      WHERE Id = :line_item_id
    ];
    if (l.Project_Name__c != null) {
      throw new AuraHandledException(
        'Project already exists! Please delete it or remove it from this Opportunity to create a new one.'
      );
    }
    if (
      l.Project_Name_Text__c == null || String.isBlank(l.Project_Name_Text__c)
    ) {
      throw new AuraHandledException('Project Name cannot be blank!');
    }
    Id ProjOwnerId;
    if (l.Opportunity.Account.Concierge_1__c == null) {
      ProjOwnerId = UserInfo.getUserId();
    } else {
      ProjOwnerId = l.Opportunity.Account.Concierge_1__c;
    }
    // Id projRecordTypeId = [Select IsSandbox FROM Organization LIMIT 1].IsSandbox ? '0121D000005fICG' : '0125Y000001bPG9';
    SFL5_Projects__c pj = new SFL5_Projects__c(
      Name = l.Project_Name_Text__c,
      RecordTypeId = '0125Y000001bPG9',
      Sales_Rep__c = l.Opportunity.Owner.Id,
      Contract__c = l.Contract__c,
      Project_Owner__c = ProjOwnerId,
      Product__c = l.Product2.Product_Category__c,
      Client__c = l.Opportunity.Account.Id,
      Project_Phase__c = 'Waiting',
      Project_Status__c = 'Waiting',
      Project_Deliverables__c = l.Special_Terms_del__c
    );

    try {
      insert pj;
      l.Project_Name__c = pj.Id;
      //if(True)throw new AuraHandledException(pj.Id);
      update l;
    } catch (DMLException error) {
      system.debug('Error: ' + error.getMessage());
    }

    return ('SUCCESS');
  }
}